// Extended Neurology Molecules - 100 additional CNS/neurology molecules
import { calculateProbabilityScores, generateMarketProjections } from './scoring';
import { type MoleculeProfile } from './moleculesData';

export const extendedNeurologyMolecules: MoleculeProfile[] = [
  // Alzheimer's Disease
  { id: "ext-neuro-001", name: "Lecanemab (Leqembi)", phase: "Approved", indication: "Early Alzheimer's Disease", therapeuticArea: "Neurology/CNS", company: "Eisai/Biogen", companyTrackRecord: 'fast', nctId: "NCT03887455", scores: calculateProbabilityScores("Approved", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("Lecanemab", "Approved", "Alzheimer's", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-amyloid beta antibody", administration: "IV infusion every 2 weeks", keyAdvantage: "Clarity AD slowing decline" } },
  { id: "ext-neuro-002", name: "Donanemab", phase: "Approved", indication: "Early Alzheimer's Disease", therapeuticArea: "Neurology/CNS", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT04437511", scores: calculateProbabilityScores("Approved", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("Donanemab", "Approved", "Alzheimer's", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-amyloid N3pG antibody", administration: "IV infusion monthly", keyAdvantage: "TRAILBLAZER-ALZ 2 success" } },
  { id: "ext-neuro-003", name: "Remternetug", phase: "Phase III", indication: "Early Alzheimer's Disease", therapeuticArea: "Neurology/CNS", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT05463731", scores: calculateProbabilityScores("Phase III", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("Remternetug", "Phase III", "Alzheimer's", 'fast'), overallScore: 0, drugInfo: { class: "Anti-amyloid antibody", administration: "SC injection", keyAdvantage: "SC administration" } },
  { id: "ext-neuro-004", name: "Gantenerumab", phase: "Phase III", indication: "Alzheimer's Disease", therapeuticArea: "Neurology/CNS", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT03444870", scores: calculateProbabilityScores("Phase III", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("Gantenerumab", "Phase III", "Alzheimer's", 'fast'), overallScore: 0, isFailed: true, drugInfo: { class: "Anti-amyloid antibody", administration: "SC injection", keyAdvantage: "SC formulation" } },
  { id: "ext-neuro-005", name: "Simufilam", phase: "Phase III", indication: "Alzheimer's Disease", therapeuticArea: "Neurology/CNS", company: "Cassava Sciences", companyTrackRecord: 'average', nctId: "NCT04994483", scores: calculateProbabilityScores("Phase III", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("Simufilam", "Phase III", "Alzheimer's", 'average'), overallScore: 0, drugInfo: { class: "Filamin A modulator", administration: "Oral", keyAdvantage: "Novel non-amyloid mechanism" } },
  { id: "ext-neuro-006", name: "AL002 (Dapirolizumab)", phase: "Phase II", indication: "Alzheimer's Disease", therapeuticArea: "Neurology/CNS", company: "Alector/AbbVie", companyTrackRecord: 'average', nctId: "NCT04592874", scores: calculateProbabilityScores("Phase II", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("AL002", "Phase II", "Alzheimer's", 'average'), overallScore: 0, drugInfo: { class: "Anti-TREM2 agonist", administration: "IV infusion", keyAdvantage: "Microglial activation" } },
  { id: "ext-neuro-007", name: "Masitinib", phase: "Phase III", indication: "Alzheimer's Disease", therapeuticArea: "Neurology/CNS", company: "AB Science", companyTrackRecord: 'average', nctId: "NCT01872598", scores: calculateProbabilityScores("Phase III", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("Masitinib", "Phase III", "Alzheimer's", 'average'), overallScore: 0, drugInfo: { class: "Tyrosine kinase inhibitor", administration: "Oral", keyAdvantage: "Mast cell modulation" } },
  { id: "ext-neuro-008", name: "Blarcamesine", phase: "Phase II/III", indication: "Alzheimer's Dementia", therapeuticArea: "Neurology/CNS", company: "Anavex", companyTrackRecord: 'average', nctId: "NCT04314934", scores: calculateProbabilityScores("Phase II", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("Blarcamesine", "Phase II", "Alzheimer's", 'average'), overallScore: 0, drugInfo: { class: "Sigma-1 receptor agonist", administration: "Oral", keyAdvantage: "Sigma-1 activation" } },
  { id: "ext-neuro-009", name: "ACI-35", phase: "Phase II", indication: "Alzheimer's Disease", therapeuticArea: "Neurology/CNS", company: "Janssen/AC Immune", companyTrackRecord: 'fast', nctId: "NCT04445831", scores: calculateProbabilityScores("Phase II", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("ACI-35", "Phase II", "Alzheimer's", 'fast'), overallScore: 0, drugInfo: { class: "Anti-tau vaccine", administration: "IM injection", keyAdvantage: "Active immunization" } },
  { id: "ext-neuro-010", name: "E2814", phase: "Phase II/III", indication: "Dominantly Inherited AD", therapeuticArea: "Neurology/CNS", company: "Eisai", companyTrackRecord: 'fast', nctId: "NCT04971733", scores: calculateProbabilityScores("Phase II", "Alzheimer's", "Neurology"), marketData: generateMarketProjections("E2814", "Phase II", "Alzheimer's", 'fast'), overallScore: 0, drugInfo: { class: "Anti-tau antibody", administration: "IV infusion", keyAdvantage: "MTBR-tau targeting" } },
  
  // Parkinson's Disease
  { id: "ext-neuro-011", name: "Prasinezumab", phase: "Phase II/III", indication: "Early Parkinson's Disease", therapeuticArea: "Neurology/CNS", company: "Roche/Prothena", companyTrackRecord: 'fast', nctId: "NCT03100149", scores: calculateProbabilityScores("Phase II", "Parkinson's", "Neurology"), marketData: generateMarketProjections("Prasinezumab", "Phase II", "Parkinson's", 'fast'), overallScore: 0, drugInfo: { class: "Anti-alpha-synuclein antibody", administration: "IV infusion", keyAdvantage: "Disease modification potential" } },
  { id: "ext-neuro-012", name: "IPX203 (Accordion Pill)", phase: "Phase III", indication: "Parkinson's Motor Fluctuations", therapeuticArea: "Neurology/CNS", company: "Amneal", companyTrackRecord: 'average', nctId: "NCT03670953", scores: calculateProbabilityScores("Phase III", "Parkinson's", "Neurology"), marketData: generateMarketProjections("IPX203", "Phase III", "Parkinson's", 'average'), overallScore: 0, drugInfo: { class: "Extended-release LD/CD", administration: "Oral", keyAdvantage: "Prolonged ON time" } },
  { id: "ext-neuro-013", name: "Tavapadon", phase: "Phase III", indication: "Parkinson's Disease", therapeuticArea: "Neurology/CNS", company: "Cerevel", companyTrackRecord: 'average', nctId: "NCT04201093", scores: calculateProbabilityScores("Phase III", "Parkinson's", "Neurology"), marketData: generateMarketProjections("Tavapadon", "Phase III", "Parkinson's", 'average'), overallScore: 0, drugInfo: { class: "D1/D5 partial agonist", administration: "Oral", keyAdvantage: "Selective D1 activation" } },
  { id: "ext-neuro-014", name: "CVN424", phase: "Phase II", indication: "Parkinson's ON-OFF", therapeuticArea: "Neurology/CNS", company: "Cerevance", companyTrackRecord: 'average', nctId: "NCT04258241", scores: calculateProbabilityScores("Phase II", "Parkinson's", "Neurology"), marketData: generateMarketProjections("CVN424", "Phase II", "Parkinson's", 'average'), overallScore: 0, drugInfo: { class: "GPR6 inverse agonist", administration: "Oral", keyAdvantage: "Non-dopaminergic" } },
  { id: "ext-neuro-015", name: "Venglustat", phase: "Phase II", indication: "GBA-Parkinson's Disease", therapeuticArea: "Neurology/CNS", company: "Sanofi", companyTrackRecord: 'fast', nctId: "NCT02906020", scores: calculateProbabilityScores("Phase II", "Parkinson's", "Neurology"), marketData: generateMarketProjections("Venglustat", "Phase II", "Parkinson's", 'fast'), overallScore: 0, drugInfo: { class: "GCS inhibitor", administration: "Oral", keyAdvantage: "GBA mutation targeting" } },
  { id: "ext-neuro-016", name: "Produodopa (foslevodopa/foscarbidopa)", phase: "Approved", indication: "Advanced Parkinson's", therapeuticArea: "Neurology/CNS", company: "AbbVie", companyTrackRecord: 'fast', nctId: "NCT04380142", scores: calculateProbabilityScores("Approved", "Parkinson's", "Neurology"), marketData: generateMarketProjections("Produodopa", "Approved", "Parkinson's", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Continuous SC LD infusion", administration: "SC infusion 24h", keyAdvantage: "Continuous delivery" } },
  { id: "ext-neuro-017", name: "Nuplazid (Pimavanserin)", phase: "Approved", indication: "Parkinson's Psychosis", therapeuticArea: "Neurology/CNS", company: "Acadia", companyTrackRecord: 'average', nctId: "NCT01174004", scores: calculateProbabilityScores("Approved", "Parkinson's Psychosis", "Neurology"), marketData: generateMarketProjections("Pimavanserin", "Approved", "Parkinson's Psychosis", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "5-HT2A inverse agonist", administration: "Oral daily", keyAdvantage: "No motor worsening" } },
  { id: "ext-neuro-018", name: "Opicapone", phase: "Approved", indication: "Parkinson's Motor Fluctuations", therapeuticArea: "Neurology/CNS", company: "Neurocrine", companyTrackRecord: 'average', nctId: "NCT01568073", scores: calculateProbabilityScores("Approved", "Parkinson's", "Neurology"), marketData: generateMarketProjections("Opicapone", "Approved", "Parkinson's", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "COMT inhibitor", administration: "Oral once daily", keyAdvantage: "Once-daily dosing" } },
  { id: "ext-neuro-019", name: "Safinamide", phase: "Approved", indication: "Parkinson's Motor Fluctuations", therapeuticArea: "Neurology/CNS", company: "Newron/US WorldMeds", companyTrackRecord: 'average', nctId: "NCT01187966", scores: calculateProbabilityScores("Approved", "Parkinson's", "Neurology"), marketData: generateMarketProjections("Safinamide", "Approved", "Parkinson's", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "MAO-B inhibitor + glutamate", administration: "Oral daily", keyAdvantage: "Dual mechanism" } },
  { id: "ext-neuro-020", name: "APL-130277 (apomorphine sublingual)", phase: "Approved", indication: "PD OFF Episodes", therapeuticArea: "Neurology/CNS", company: "Sunovion", companyTrackRecord: 'average', nctId: "NCT02469090", scores: calculateProbabilityScores("Approved", "Parkinson's", "Neurology"), marketData: generateMarketProjections("APL-130277", "Approved", "Parkinson's", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Dopamine agonist", administration: "Sublingual film", keyAdvantage: "Rapid OFF rescue" } },
  
  // Multiple Sclerosis
  { id: "ext-neuro-021", name: "Ocrelizumab", phase: "Approved", indication: "Relapsing and Primary Progressive MS", therapeuticArea: "Neurology/CNS", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT01194570", scores: calculateProbabilityScores("Approved", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Ocrelizumab", "Approved", "Multiple Sclerosis", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CD20 antibody", administration: "IV infusion every 6 months", keyAdvantage: "First PPMS therapy" } },
  { id: "ext-neuro-022", name: "Ofatumumab", phase: "Approved", indication: "Relapsing MS", therapeuticArea: "Neurology/CNS", company: "Novartis", companyTrackRecord: 'fast', nctId: "NCT02792218", scores: calculateProbabilityScores("Approved", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Ofatumumab", "Approved", "Multiple Sclerosis", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CD20 antibody", administration: "SC monthly", keyAdvantage: "Self-administered SC" } },
  { id: "ext-neuro-023", name: "Ublituximab", phase: "Approved", indication: "Relapsing MS", therapeuticArea: "Neurology/CNS", company: "TG Therapeutics", companyTrackRecord: 'average', nctId: "NCT03277261", scores: calculateProbabilityScores("Approved", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Ublituximab", "Approved", "Multiple Sclerosis", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CD20 antibody", administration: "IV 1-hour infusion", keyAdvantage: "1-hour infusion" } },
  { id: "ext-neuro-024", name: "Fenebrutinib", phase: "Phase III", indication: "Relapsing and Progressive MS", therapeuticArea: "Neurology/CNS", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT04544449", scores: calculateProbabilityScores("Phase III", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Fenebrutinib", "Phase III", "Multiple Sclerosis", 'fast'), overallScore: 0, drugInfo: { class: "BTK inhibitor", administration: "Oral", keyAdvantage: "CNS penetrant" } },
  { id: "ext-neuro-025", name: "Tolebrutinib", phase: "Phase III", indication: "Relapsing and Progressive MS", therapeuticArea: "Neurology/CNS", company: "Sanofi", companyTrackRecord: 'fast', nctId: "NCT04410978", scores: calculateProbabilityScores("Phase III", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Tolebrutinib", "Phase III", "Multiple Sclerosis", 'fast'), overallScore: 0, drugInfo: { class: "BTK inhibitor", administration: "Oral", keyAdvantage: "Brain-penetrant" } },
  { id: "ext-neuro-026", name: "Evobrutinib", phase: "Phase III", indication: "Relapsing MS", therapeuticArea: "Neurology/CNS", company: "Merck KGaA", companyTrackRecord: 'average', nctId: "NCT04338022", scores: calculateProbabilityScores("Phase III", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Evobrutinib", "Phase III", "Multiple Sclerosis", 'average'), overallScore: 0, drugInfo: { class: "BTK inhibitor", administration: "Oral", keyAdvantage: "B-cell & microglia modulation" } },
  { id: "ext-neuro-027", name: "Frexalimab", phase: "Phase III", indication: "Relapsing MS", therapeuticArea: "Neurology/CNS", company: "Sanofi", companyTrackRecord: 'fast', nctId: "NCT05419141", scores: calculateProbabilityScores("Phase III", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Frexalimab", "Phase III", "Multiple Sclerosis", 'fast'), overallScore: 0, drugInfo: { class: "Anti-CD40L antibody", administration: "SC or IV", keyAdvantage: "Near-complete lesion suppression" } },
  { id: "ext-neuro-028", name: "Ozanimod", phase: "Approved", indication: "Relapsing MS", therapeuticArea: "Neurology/CNS", company: "BMS", companyTrackRecord: 'fast', nctId: "NCT02047734", scores: calculateProbabilityScores("Approved", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Ozanimod", "Approved", "Multiple Sclerosis", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "S1P receptor modulator", administration: "Oral daily", keyAdvantage: "S1P1,5 selectivity" } },
  { id: "ext-neuro-029", name: "Ponesimod", phase: "Approved", indication: "Relapsing MS", therapeuticArea: "Neurology/CNS", company: "Janssen", companyTrackRecord: 'fast', nctId: "NCT02425644", scores: calculateProbabilityScores("Approved", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Ponesimod", "Approved", "Multiple Sclerosis", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "S1P1 modulator", administration: "Oral daily", keyAdvantage: "Rapid elimination" } },
  { id: "ext-neuro-030", name: "Siponimod", phase: "Approved", indication: "Secondary Progressive MS", therapeuticArea: "Neurology/CNS", company: "Novartis", companyTrackRecord: 'fast', nctId: "NCT01665144", scores: calculateProbabilityScores("Approved", "Multiple Sclerosis", "Neurology"), marketData: generateMarketProjections("Siponimod", "Approved", "Multiple Sclerosis", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "S1P1,5 modulator", administration: "Oral daily", keyAdvantage: "SPMS indication" } },
  
  // ALS
  { id: "ext-neuro-031", name: "Tofersen", phase: "Approved", indication: "SOD1-ALS", therapeuticArea: "Neurology/CNS", company: "Biogen", companyTrackRecord: 'fast', nctId: "NCT02623699", scores: calculateProbabilityScores("Approved", "ALS", "Neurology"), marketData: generateMarketProjections("Tofersen", "Approved", "ALS", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Antisense oligonucleotide", administration: "Intrathecal monthly", keyAdvantage: "SOD1 gene silencing" } },
  { id: "ext-neuro-032", name: "Relyvrio (AMX0035)", phase: "Approved", indication: "ALS", therapeuticArea: "Neurology/CNS", company: "Amylyx", companyTrackRecord: 'average', nctId: "NCT03127514", scores: calculateProbabilityScores("Approved", "ALS", "Neurology"), marketData: generateMarketProjections("Relyvrio", "Approved", "ALS", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Sodium phenylbutyrate/taurursodiol", administration: "Oral", keyAdvantage: "Dual-mechanism" } },
  { id: "ext-neuro-033", name: "Jacifusen", phase: "Phase III", indication: "FUS-ALS", therapeuticArea: "Neurology/CNS", company: "Ionis/Biogen", companyTrackRecord: 'fast', nctId: "NCT04768972", scores: calculateProbabilityScores("Phase III", "ALS", "Neurology"), marketData: generateMarketProjections("Jacifusen", "Phase III", "ALS", 'fast'), overallScore: 0, drugInfo: { class: "Antisense oligonucleotide", administration: "Intrathecal", keyAdvantage: "FUS mutation targeting" } },
  { id: "ext-neuro-034", name: "Pridopidine", phase: "Phase II/III", indication: "ALS", therapeuticArea: "Neurology/CNS", company: "Prilenia", companyTrackRecord: 'average', nctId: "NCT04297683", scores: calculateProbabilityScores("Phase II", "ALS", "Neurology"), marketData: generateMarketProjections("Pridopidine", "Phase II", "ALS", 'average'), overallScore: 0, drugInfo: { class: "Sigma-1 receptor agonist", administration: "Oral", keyAdvantage: "Neuroprotective" } },
  { id: "ext-neuro-035", name: "Zilucoplan", phase: "Phase III", indication: "ALS", therapeuticArea: "Neurology/CNS", company: "UCB", companyTrackRecord: 'fast', nctId: "NCT04436497", scores: calculateProbabilityScores("Phase III", "ALS", "Neurology"), marketData: generateMarketProjections("Zilucoplan", "Phase III", "ALS", 'fast'), overallScore: 0, drugInfo: { class: "C5 complement inhibitor", administration: "SC daily", keyAdvantage: "Complement modulation" } },
  
  // Epilepsy
  { id: "ext-neuro-036", name: "Cenobamate", phase: "Approved", indication: "Focal Onset Seizures", therapeuticArea: "Neurology/CNS", company: "SK Biopharmaceuticals", companyTrackRecord: 'average', nctId: "NCT01866111", scores: calculateProbabilityScores("Approved", "Epilepsy", "Neurology"), marketData: generateMarketProjections("Cenobamate", "Approved", "Epilepsy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Sodium channel blocker + GABA modulator", administration: "Oral daily", keyAdvantage: "High seizure-free rates" } },
  { id: "ext-neuro-037", name: "Fenfluramine", phase: "Approved", indication: "Dravet Syndrome/LGS", therapeuticArea: "Neurology/CNS", company: "Zogenix/UCB", companyTrackRecord: 'average', nctId: "NCT02682927", scores: calculateProbabilityScores("Approved", "Epilepsy", "Neurology"), marketData: generateMarketProjections("Fenfluramine", "Approved", "Epilepsy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Serotonin modulator", administration: "Oral solution", keyAdvantage: "Dravet efficacy" } },
  { id: "ext-neuro-038", name: "Ganaxolone", phase: "Approved", indication: "CDKL5 Deficiency", therapeuticArea: "Neurology/CNS", company: "Marinus", companyTrackRecord: 'average', nctId: "NCT03572933", scores: calculateProbabilityScores("Approved", "Epilepsy", "Neurology"), marketData: generateMarketProjections("Ganaxolone", "Approved", "Epilepsy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "GABA-A receptor modulator", administration: "Oral suspension", keyAdvantage: "First CDKL5 therapy" } },
  { id: "ext-neuro-039", name: "Epidiolex (Cannabidiol)", phase: "Approved", indication: "Dravet/LGS/TSC Seizures", therapeuticArea: "Neurology/CNS", company: "Jazz", companyTrackRecord: 'average', nctId: "NCT02224560", scores: calculateProbabilityScores("Approved", "Epilepsy", "Neurology"), marketData: generateMarketProjections("Epidiolex", "Approved", "Epilepsy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Cannabinoid", administration: "Oral solution", keyAdvantage: "First FDA-approved CBD" } },
  { id: "ext-neuro-040", name: "Staccato Alprazolam", phase: "Approved", indication: "Seizure Clusters", therapeuticArea: "Neurology/CNS", company: "UCB", companyTrackRecord: 'fast', nctId: "NCT02262117", scores: calculateProbabilityScores("Approved", "Epilepsy", "Neurology"), marketData: generateMarketProjections("Staccato Alprazolam", "Approved", "Epilepsy", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Benzodiazepine", administration: "Inhalation", keyAdvantage: "Rapid seizure rescue" } },
  
  // Migraine
  { id: "ext-neuro-041", name: "Erenumab", phase: "Approved", indication: "Migraine Prevention", therapeuticArea: "Neurology/CNS", company: "Amgen/Novartis", companyTrackRecord: 'fast', nctId: "NCT02456740", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Erenumab", "Approved", "Migraine", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CGRP receptor antibody", administration: "SC monthly", keyAdvantage: "First CGRP therapy" } },
  { id: "ext-neuro-042", name: "Fremanezumab", phase: "Approved", indication: "Migraine Prevention", therapeuticArea: "Neurology/CNS", company: "Teva", companyTrackRecord: 'average', nctId: "NCT02629861", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Fremanezumab", "Approved", "Migraine", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CGRP antibody", administration: "SC monthly/quarterly", keyAdvantage: "Quarterly dosing option" } },
  { id: "ext-neuro-043", name: "Galcanezumab", phase: "Approved", indication: "Migraine/Cluster Prevention", therapeuticArea: "Neurology/CNS", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT02614183", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Galcanezumab", "Approved", "Migraine", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CGRP antibody", administration: "SC monthly", keyAdvantage: "Cluster headache indication" } },
  { id: "ext-neuro-044", name: "Eptinezumab", phase: "Approved", indication: "Migraine Prevention", therapeuticArea: "Neurology/CNS", company: "Lundbeck", companyTrackRecord: 'average', nctId: "NCT02559895", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Eptinezumab", "Approved", "Migraine", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CGRP antibody", administration: "IV quarterly", keyAdvantage: "Rapid onset" } },
  { id: "ext-neuro-045", name: "Atogepant", phase: "Approved", indication: "Episodic/Chronic Migraine", therapeuticArea: "Neurology/CNS", company: "AbbVie", companyTrackRecord: 'fast', nctId: "NCT03777059", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Atogepant", "Approved", "Migraine", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CGRP receptor antagonist", administration: "Oral daily", keyAdvantage: "Oral prevention" } },
  { id: "ext-neuro-046", name: "Rimegepant", phase: "Approved", indication: "Migraine Acute/Prevention", therapeuticArea: "Neurology/CNS", company: "Pfizer", companyTrackRecord: 'fast', nctId: "NCT03237845", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Rimegepant", "Approved", "Migraine", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CGRP receptor antagonist", administration: "Oral/ODT", keyAdvantage: "Acute and preventive use" } },
  { id: "ext-neuro-047", name: "Ubrogepant", phase: "Approved", indication: "Acute Migraine", therapeuticArea: "Neurology/CNS", company: "AbbVie", companyTrackRecord: 'fast', nctId: "NCT02828020", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Ubrogepant", "Approved", "Migraine", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CGRP receptor antagonist", administration: "Oral", keyAdvantage: "First oral acute gepant" } },
  { id: "ext-neuro-048", name: "Zavegepant", phase: "Approved", indication: "Acute Migraine", therapeuticArea: "Neurology/CNS", company: "Pfizer", companyTrackRecord: 'fast', nctId: "NCT04571060", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Zavegepant", "Approved", "Migraine", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CGRP receptor antagonist", administration: "Nasal spray", keyAdvantage: "Intranasal delivery" } },
  { id: "ext-neuro-049", name: "Lasmiditan", phase: "Approved", indication: "Acute Migraine", therapeuticArea: "Neurology/CNS", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT02439320", scores: calculateProbabilityScores("Approved", "Migraine", "Neurology"), marketData: generateMarketProjections("Lasmiditan", "Approved", "Migraine", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "5-HT1F agonist", administration: "Oral", keyAdvantage: "No vasoconstriction" } },
  { id: "ext-neuro-050", name: "Atibeneptine", phase: "Phase III", indication: "Migraine Prevention", therapeuticArea: "Neurology/CNS", company: "Antibe Therapeutics", companyTrackRecord: 'average', nctId: "NCT04415866", scores: calculateProbabilityScores("Phase III", "Migraine", "Neurology"), marketData: generateMarketProjections("Atibeneptine", "Phase III", "Migraine", 'average'), overallScore: 0, drugInfo: { class: "CGRP modulator", administration: "Oral", keyAdvantage: "H2S-releasing" } },
  
  // Huntington's Disease
  { id: "ext-neuro-051", name: "Tominersen", phase: "Phase III", indication: "Huntington's Disease", therapeuticArea: "Neurology/CNS", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT03761849", scores: calculateProbabilityScores("Phase III", "Huntington's", "Neurology"), marketData: generateMarketProjections("Tominersen", "Phase III", "Huntington's", 'fast'), overallScore: 0, isFailed: true, drugInfo: { class: "Antisense oligonucleotide", administration: "Intrathecal", keyAdvantage: "HTT lowering" } },
  { id: "ext-neuro-052", name: "Valbenazine", phase: "Approved", indication: "Tardive Dyskinesia/Chorea", therapeuticArea: "Neurology/CNS", company: "Neurocrine", companyTrackRecord: 'average', nctId: "NCT02274558", scores: calculateProbabilityScores("Approved", "Movement Disorder", "Neurology"), marketData: generateMarketProjections("Valbenazine", "Approved", "Movement Disorder", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "VMAT2 inhibitor", administration: "Oral daily", keyAdvantage: "First TD approval" } },
  { id: "ext-neuro-053", name: "Deutetrabenazine", phase: "Approved", indication: "Huntington's Chorea/TD", therapeuticArea: "Neurology/CNS", company: "Teva", companyTrackRecord: 'average', nctId: "NCT01795859", scores: calculateProbabilityScores("Approved", "Huntington's", "Neurology"), marketData: generateMarketProjections("Deutetrabenazine", "Approved", "Huntington's", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "VMAT2 inhibitor", administration: "Oral twice daily", keyAdvantage: "Improved tolerability" } },
  { id: "ext-neuro-054", name: "Pridopidine (HD)", phase: "Phase III", indication: "Huntington's Disease", therapeuticArea: "Neurology/CNS", company: "Prilenia", companyTrackRecord: 'average', nctId: "NCT04556656", scores: calculateProbabilityScores("Phase III", "Huntington's", "Neurology"), marketData: generateMarketProjections("Pridopidine HD", "Phase III", "Huntington's", 'average'), overallScore: 0, drugInfo: { class: "Sigma-1 receptor agonist", administration: "Oral", keyAdvantage: "Functional benefit" } },
  { id: "ext-neuro-055", name: "PTC518", phase: "Phase II", indication: "Huntington's Disease", therapeuticArea: "Neurology/CNS", company: "PTC Therapeutics", companyTrackRecord: 'average', nctId: "NCT05358717", scores: calculateProbabilityScores("Phase II", "Huntington's", "Neurology"), marketData: generateMarketProjections("PTC518", "Phase II", "Huntington's", 'average'), overallScore: 0, drugInfo: { class: "HTT splicing modifier", administration: "Oral", keyAdvantage: "Oral HTT lowering" } },
  
  // Spinal Muscular Atrophy
  { id: "ext-neuro-056", name: "Nusinersen", phase: "Approved", indication: "SMA (all types)", therapeuticArea: "Neurology/CNS", company: "Biogen", companyTrackRecord: 'fast', nctId: "NCT02193074", scores: calculateProbabilityScores("Approved", "SMA", "Neurology"), marketData: generateMarketProjections("Nusinersen", "Approved", "SMA", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Antisense oligonucleotide", administration: "Intrathecal every 4 months", keyAdvantage: "First SMA therapy" } },
  { id: "ext-neuro-057", name: "Onasemnogene Abeparvovec", phase: "Approved", indication: "SMA Type 1", therapeuticArea: "Neurology/CNS", company: "Novartis", companyTrackRecord: 'fast', nctId: "NCT03306277", scores: calculateProbabilityScores("Approved", "SMA", "Neurology"), marketData: generateMarketProjections("Zolgensma", "Approved", "SMA", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "AAV9 gene therapy", administration: "Single IV infusion", keyAdvantage: "One-time treatment" } },
  { id: "ext-neuro-058", name: "Risdiplam", phase: "Approved", indication: "SMA (all types)", therapeuticArea: "Neurology/CNS", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT02913482", scores: calculateProbabilityScores("Approved", "SMA", "Neurology"), marketData: generateMarketProjections("Risdiplam", "Approved", "SMA", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "SMN2 splicing modifier", administration: "Oral daily", keyAdvantage: "Oral administration" } },
  { id: "ext-neuro-059", name: "Apitegromab", phase: "Phase III", indication: "SMA", therapeuticArea: "Neurology/CNS", company: "Scholar Rock", companyTrackRecord: 'average', nctId: "NCT05156320", scores: calculateProbabilityScores("Phase III", "SMA", "Neurology"), marketData: generateMarketProjections("Apitegromab", "Phase III", "SMA", 'average'), overallScore: 0, drugInfo: { class: "Anti-myostatin antibody", administration: "IV infusion", keyAdvantage: "Muscle enhancement" } },
  { id: "ext-neuro-060", name: "Taldefgrobep alfa", phase: "Phase II/III", indication: "SMA", therapeuticArea: "Neurology/CNS", company: "BioMarin", companyTrackRecord: 'average', nctId: "NCT05337553", scores: calculateProbabilityScores("Phase II", "SMA", "Neurology"), marketData: generateMarketProjections("Taldefgrobep alfa", "Phase II", "SMA", 'average'), overallScore: 0, drugInfo: { class: "Anti-myostatin adnectin", administration: "SC injection", keyAdvantage: "Myostatin inhibition" } },
  
  // Duchenne Muscular Dystrophy
  { id: "ext-neuro-061", name: "Eteplirsen", phase: "Approved", indication: "DMD (Exon 51)", therapeuticArea: "Neurology/CNS", company: "Sarepta", companyTrackRecord: 'average', nctId: "NCT01396239", scores: calculateProbabilityScores("Approved", "DMD", "Neurology"), marketData: generateMarketProjections("Eteplirsen", "Approved", "DMD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Exon-skipping ASO", administration: "IV weekly", keyAdvantage: "First DMD exon-skipper" } },
  { id: "ext-neuro-062", name: "Golodirsen", phase: "Approved", indication: "DMD (Exon 53)", therapeuticArea: "Neurology/CNS", company: "Sarepta", companyTrackRecord: 'average', nctId: "NCT02310906", scores: calculateProbabilityScores("Approved", "DMD", "Neurology"), marketData: generateMarketProjections("Golodirsen", "Approved", "DMD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Exon-skipping ASO", administration: "IV weekly", keyAdvantage: "Exon 53 targeting" } },
  { id: "ext-neuro-063", name: "Casimersen", phase: "Approved", indication: "DMD (Exon 45)", therapeuticArea: "Neurology/CNS", company: "Sarepta", companyTrackRecord: 'average', nctId: "NCT03532308", scores: calculateProbabilityScores("Approved", "DMD", "Neurology"), marketData: generateMarketProjections("Casimersen", "Approved", "DMD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Exon-skipping ASO", administration: "IV weekly", keyAdvantage: "Exon 45 targeting" } },
  { id: "ext-neuro-064", name: "Delandistrogene Moxeparvovec", phase: "Approved", indication: "DMD", therapeuticArea: "Neurology/CNS", company: "Sarepta", companyTrackRecord: 'average', nctId: "NCT03375164", scores: calculateProbabilityScores("Approved", "DMD", "Neurology"), marketData: generateMarketProjections("Elevidys", "Approved", "DMD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "AAV gene therapy", administration: "Single IV infusion", keyAdvantage: "Micro-dystrophin expression" } },
  { id: "ext-neuro-065", name: "Vamorolone", phase: "Approved", indication: "DMD", therapeuticArea: "Neurology/CNS", company: "Santhera", companyTrackRecord: 'average', nctId: "NCT03439670", scores: calculateProbabilityScores("Approved", "DMD", "Neurology"), marketData: generateMarketProjections("Vamorolone", "Approved", "DMD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Dissociative steroid", administration: "Oral", keyAdvantage: "Reduced steroid side effects" } },
  
  // Stroke
  { id: "ext-neuro-066", name: "Tenecteplase (Stroke)", phase: "Phase III", indication: "Acute Ischemic Stroke", therapeuticArea: "Neurology/CNS", company: "Genentech", companyTrackRecord: 'fast', nctId: "NCT03861507", scores: calculateProbabilityScores("Phase III", "Stroke", "Neurology"), marketData: generateMarketProjections("Tenecteplase Stroke", "Phase III", "Stroke", 'fast'), overallScore: 0, drugInfo: { class: "Thrombolytic", administration: "IV bolus", keyAdvantage: "Single bolus vs alteplase infusion" } },
  { id: "ext-neuro-067", name: "3K3A-APC", phase: "Phase III", indication: "Ischemic Stroke", therapeuticArea: "Neurology/CNS", company: "ZZ Biotech", companyTrackRecord: 'average', nctId: "NCT02222714", scores: calculateProbabilityScores("Phase III", "Stroke", "Neurology"), marketData: generateMarketProjections("3K3A-APC", "Phase III", "Stroke", 'average'), overallScore: 0, drugInfo: { class: "Activated protein C variant", administration: "IV infusion", keyAdvantage: "Neuroprotection" } },
  { id: "ext-neuro-068", name: "ApTOLL", phase: "Phase II", indication: "Ischemic Stroke", therapeuticArea: "Neurology/CNS", company: "Aptoll", companyTrackRecord: 'average', nctId: "NCT04734548", scores: calculateProbabilityScores("Phase II", "Stroke", "Neurology"), marketData: generateMarketProjections("ApTOLL", "Phase II", "Stroke", 'average'), overallScore: 0, drugInfo: { class: "TLR4 antagonist aptamer", administration: "IV", keyAdvantage: "Anti-inflammatory neuroprotection" } },
  
  // Neuropathic Pain
  { id: "ext-neuro-069", name: "Tanezumab", phase: "Phase III", indication: "Chronic Pain", therapeuticArea: "Neurology/CNS", company: "Pfizer/Lilly", companyTrackRecord: 'fast', nctId: "NCT02709486", scores: calculateProbabilityScores("Phase III", "Pain", "Neurology"), marketData: generateMarketProjections("Tanezumab", "Phase III", "Pain", 'fast'), overallScore: 0, isFailed: true, drugInfo: { class: "Anti-NGF antibody", administration: "SC", keyAdvantage: "NGF pathway" } },
  { id: "ext-neuro-070", name: "VX-548", phase: "Phase III", indication: "Neuropathic Pain", therapeuticArea: "Neurology/CNS", company: "Vertex", companyTrackRecord: 'fast', nctId: "NCT05652998", scores: calculateProbabilityScores("Phase III", "Pain", "Neurology"), marketData: generateMarketProjections("VX-548", "Phase III", "Pain", 'fast'), overallScore: 0, drugInfo: { class: "Nav1.8 inhibitor", administration: "Oral", keyAdvantage: "Non-opioid mechanism" } },
  
  // Myasthenia Gravis
  { id: "ext-neuro-071", name: "Efgartigimod", phase: "Approved", indication: "Generalized Myasthenia Gravis", therapeuticArea: "Neurology/CNS", company: "argenx", companyTrackRecord: 'average', nctId: "NCT03669588", scores: calculateProbabilityScores("Approved", "Myasthenia Gravis", "Neurology"), marketData: generateMarketProjections("Efgartigimod", "Approved", "Myasthenia Gravis", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "FcRn antagonist", administration: "IV weekly", keyAdvantage: "IgG reduction" } },
  { id: "ext-neuro-072", name: "Rozanolixizumab", phase: "Approved", indication: "Generalized Myasthenia Gravis", therapeuticArea: "Neurology/CNS", company: "UCB", companyTrackRecord: 'fast', nctId: "NCT03971422", scores: calculateProbabilityScores("Approved", "Myasthenia Gravis", "Neurology"), marketData: generateMarketProjections("Rozanolixizumab", "Approved", "Myasthenia Gravis", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "FcRn antagonist", administration: "SC weekly", keyAdvantage: "SC administration" } },
  { id: "ext-neuro-073", name: "Zilucoplan (MG)", phase: "Approved", indication: "Generalized Myasthenia Gravis", therapeuticArea: "Neurology/CNS", company: "UCB", companyTrackRecord: 'fast', nctId: "NCT04115293", scores: calculateProbabilityScores("Approved", "Myasthenia Gravis", "Neurology"), marketData: generateMarketProjections("Zilucoplan MG", "Approved", "Myasthenia Gravis", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "C5 complement inhibitor", administration: "SC daily", keyAdvantage: "SC complement inhibition" } },
  { id: "ext-neuro-074", name: "Ravulizumab (MG)", phase: "Approved", indication: "Generalized Myasthenia Gravis", therapeuticArea: "Neurology/CNS", company: "Alexion", companyTrackRecord: 'fast', nctId: "NCT03920293", scores: calculateProbabilityScores("Approved", "Myasthenia Gravis", "Neurology"), marketData: generateMarketProjections("Ravulizumab MG", "Approved", "Myasthenia Gravis", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "C5 complement inhibitor", administration: "IV every 8 weeks", keyAdvantage: "8-week dosing" } },
  { id: "ext-neuro-075", name: "Nipocalimab", phase: "Phase III", indication: "Generalized Myasthenia Gravis", therapeuticArea: "Neurology/CNS", company: "Janssen", companyTrackRecord: 'fast', nctId: "NCT04951622", scores: calculateProbabilityScores("Phase III", "Myasthenia Gravis", "Neurology"), marketData: generateMarketProjections("Nipocalimab", "Phase III", "Myasthenia Gravis", 'fast'), overallScore: 0, drugInfo: { class: "FcRn antagonist", administration: "IV", keyAdvantage: "Maternal-fetal indication" } },
  
  // CIDP/Peripheral Neuropathy
  { id: "ext-neuro-076", name: "Efgartigimod (CIDP)", phase: "Phase III", indication: "CIDP", therapeuticArea: "Neurology/CNS", company: "argenx", companyTrackRecord: 'average', nctId: "NCT04281472", scores: calculateProbabilityScores("Phase III", "CIDP", "Neurology"), marketData: generateMarketProjections("Efgartigimod CIDP", "Phase III", "CIDP", 'average'), overallScore: 0, drugInfo: { class: "FcRn antagonist", administration: "SC/IV", keyAdvantage: "IVIg alternative" } },
  { id: "ext-neuro-077", name: "Rozanolixizumab (CIDP)", phase: "Phase III", indication: "CIDP", therapeuticArea: "Neurology/CNS", company: "UCB", companyTrackRecord: 'fast', nctId: "NCT05032183", scores: calculateProbabilityScores("Phase III", "CIDP", "Neurology"), marketData: generateMarketProjections("Rozanolixizumab CIDP", "Phase III", "CIDP", 'fast'), overallScore: 0, drugInfo: { class: "FcRn antagonist", administration: "SC", keyAdvantage: "SC convenience" } },
  
  // Narcolepsy/Sleep
  { id: "ext-neuro-078", name: "Solriamfetol", phase: "Approved", indication: "Narcolepsy/OSA EDS", therapeuticArea: "Neurology/CNS", company: "Jazz", companyTrackRecord: 'average', nctId: "NCT02348593", scores: calculateProbabilityScores("Approved", "Narcolepsy", "Neurology"), marketData: generateMarketProjections("Solriamfetol", "Approved", "Narcolepsy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "DNRI", administration: "Oral daily", keyAdvantage: "Non-scheduled option" } },
  { id: "ext-neuro-079", name: "Pitolisant", phase: "Approved", indication: "Narcolepsy", therapeuticArea: "Neurology/CNS", company: "Harmony", companyTrackRecord: 'average', nctId: "NCT01067222", scores: calculateProbabilityScores("Approved", "Narcolepsy", "Neurology"), marketData: generateMarketProjections("Pitolisant", "Approved", "Narcolepsy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "H3 receptor antagonist", administration: "Oral daily", keyAdvantage: "Non-stimulant" } },
  { id: "ext-neuro-080", name: "Sodium Oxybate (Once Nightly)", phase: "Approved", indication: "Narcolepsy", therapeuticArea: "Neurology/CNS", company: "Avadel", companyTrackRecord: 'average', nctId: "NCT02720744", scores: calculateProbabilityScores("Approved", "Narcolepsy", "Neurology"), marketData: generateMarketProjections("Lumryz", "Approved", "Narcolepsy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Extended-release GHB", administration: "Oral once nightly", keyAdvantage: "Once-nightly dosing" } },
  
  // Essential Tremor
  { id: "ext-neuro-081", name: "CALA Trio (Device)", phase: "Approved", indication: "Essential Tremor", therapeuticArea: "Neurology/CNS", company: "CALA Health", companyTrackRecord: 'average', nctId: "NCT02839265", scores: calculateProbabilityScores("Approved", "Essential Tremor", "Neurology"), marketData: generateMarketProjections("CALA Trio", "Approved", "Essential Tremor", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Wearable neuromodulator", administration: "Wrist device", keyAdvantage: "Non-invasive stimulation" } },
  { id: "ext-neuro-082", name: "CAD-1883", phase: "Phase II", indication: "Essential Tremor", therapeuticArea: "Neurology/CNS", company: "Cadent Therapeutics", companyTrackRecord: 'average', nctId: "NCT04088539", scores: calculateProbabilityScores("Phase II", "Essential Tremor", "Neurology"), marketData: generateMarketProjections("CAD-1883", "Phase II", "Essential Tremor", 'average'), overallScore: 0, drugInfo: { class: "SK channel modulator", administration: "Oral", keyAdvantage: "Novel mechanism" } },
  
  // Restless Legs Syndrome
  { id: "ext-neuro-083", name: "Dipyridamole ER", phase: "Phase III", indication: "Restless Legs Syndrome", therapeuticArea: "Neurology/CNS", company: "Neuropathix", companyTrackRecord: 'average', nctId: "NCT04533711", scores: calculateProbabilityScores("Phase III", "RLS", "Neurology"), marketData: generateMarketProjections("Dipyridamole RLS", "Phase III", "RLS", 'average'), overallScore: 0, drugInfo: { class: "ENT1 inhibitor", administration: "Oral", keyAdvantage: "Adenosine modulation" } },
  
  // Friedreich's Ataxia
  { id: "ext-neuro-084", name: "Omaveloxolone", phase: "Approved", indication: "Friedreich's Ataxia", therapeuticArea: "Neurology/CNS", company: "Reata/Biogen", companyTrackRecord: 'average', nctId: "NCT02255435", scores: calculateProbabilityScores("Approved", "Friedreich's Ataxia", "Neurology"), marketData: generateMarketProjections("Omaveloxolone", "Approved", "Friedreich's Ataxia", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Nrf2 activator", administration: "Oral daily", keyAdvantage: "First FA therapy" } },
  
  // Rett Syndrome
  { id: "ext-neuro-085", name: "Trofinetide", phase: "Approved", indication: "Rett Syndrome", therapeuticArea: "Neurology/CNS", company: "Acadia", companyTrackRecord: 'average', nctId: "NCT04181723", scores: calculateProbabilityScores("Approved", "Rett Syndrome", "Neurology"), marketData: generateMarketProjections("Trofinetide", "Approved", "Rett Syndrome", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Synthetic analog of IGF-1", administration: "Oral solution", keyAdvantage: "First Rett therapy" } },
  
  // Ataxia-Telangiectasia
  { id: "ext-neuro-086", name: "EryDex (Dexamethasone)", phase: "Phase III", indication: "Ataxia-Telangiectasia", therapeuticArea: "Neurology/CNS", company: "EryDel", companyTrackRecord: 'average', nctId: "NCT02770807", scores: calculateProbabilityScores("Phase III", "Ataxia", "Neurology"), marketData: generateMarketProjections("EryDex", "Phase III", "Ataxia", 'average'), overallScore: 0, drugInfo: { class: "RBC-encapsulated dexamethasone", administration: "IV infusion", keyAdvantage: "Reduced steroid side effects" } },
  
  // Autism Spectrum Disorder
  { id: "ext-neuro-087", name: "Balovaptan", phase: "Phase III", indication: "Autism Spectrum Disorder", therapeuticArea: "Neurology/CNS", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT03504917", scores: calculateProbabilityScores("Phase III", "ASD", "Neurology"), marketData: generateMarketProjections("Balovaptan", "Phase III", "ASD", 'fast'), overallScore: 0, isFailed: true, drugInfo: { class: "V1a receptor antagonist", administration: "Oral", keyAdvantage: "Social function" } },
  { id: "ext-neuro-088", name: "Arbaclofen ER", phase: "Phase III", indication: "Autism Spectrum Disorder", therapeuticArea: "Neurology/CNS", company: "Seaside", companyTrackRecord: 'average', nctId: "NCT03682978", scores: calculateProbabilityScores("Phase III", "ASD", "Neurology"), marketData: generateMarketProjections("Arbaclofen ER", "Phase III", "ASD", 'average'), overallScore: 0, drugInfo: { class: "GABA-B agonist", administration: "Oral", keyAdvantage: "Social/behavioral" } },
  
  // Adrenoleukodystrophy
  { id: "ext-neuro-089", name: "Elivaldogene Autotemcel", phase: "Approved", indication: "Cerebral ALD", therapeuticArea: "Neurology/CNS", company: "bluebird bio", companyTrackRecord: 'average', nctId: "NCT01896102", scores: calculateProbabilityScores("Approved", "ALD", "Neurology"), marketData: generateMarketProjections("Skysona", "Approved", "ALD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Lentiviral gene therapy", administration: "Single IV infusion", keyAdvantage: "Gene correction" } },
  
  // Hereditary Transthyretin Amyloidosis
  { id: "ext-neuro-090", name: "Patisiran", phase: "Approved", indication: "hATTR Polyneuropathy", therapeuticArea: "Neurology/CNS", company: "Alnylam", companyTrackRecord: 'fast', nctId: "NCT01960348", scores: calculateProbabilityScores("Approved", "hATTR", "Neurology"), marketData: generateMarketProjections("Patisiran", "Approved", "hATTR", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "RNAi therapeutic", administration: "IV every 3 weeks", keyAdvantage: "First RNAi approval" } },
  { id: "ext-neuro-091", name: "Vutrisiran", phase: "Approved", indication: "hATTR Polyneuropathy", therapeuticArea: "Neurology/CNS", company: "Alnylam", companyTrackRecord: 'fast', nctId: "NCT03759379", scores: calculateProbabilityScores("Approved", "hATTR", "Neurology"), marketData: generateMarketProjections("Vutrisiran", "Approved", "hATTR", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "RNAi therapeutic", administration: "SC every 3 months", keyAdvantage: "Quarterly SC dosing" } },
  { id: "ext-neuro-092", name: "Inotersen", phase: "Approved", indication: "hATTR Polyneuropathy", therapeuticArea: "Neurology/CNS", company: "Ionis/Akcea", companyTrackRecord: 'fast', nctId: "NCT01737398", scores: calculateProbabilityScores("Approved", "hATTR", "Neurology"), marketData: generateMarketProjections("Inotersen", "Approved", "hATTR", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Antisense oligonucleotide", administration: "SC weekly", keyAdvantage: "Weekly SC" } },
  { id: "ext-neuro-093", name: "Eplontersen", phase: "Approved", indication: "hATTR Polyneuropathy", therapeuticArea: "Neurology/CNS", company: "Ionis/AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT04136184", scores: calculateProbabilityScores("Approved", "hATTR", "Neurology"), marketData: generateMarketProjections("Eplontersen", "Approved", "hATTR", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Ligand-conjugated ASO", administration: "SC monthly", keyAdvantage: "Monthly SC" } },
  { id: "ext-neuro-094", name: "Tafamidis", phase: "Approved", indication: "ATTR Polyneuropathy/CM", therapeuticArea: "Neurology/CNS", company: "Pfizer", companyTrackRecord: 'fast', nctId: "NCT00409175", scores: calculateProbabilityScores("Approved", "ATTR", "Neurology"), marketData: generateMarketProjections("Tafamidis", "Approved", "ATTR", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TTR stabilizer", administration: "Oral daily", keyAdvantage: "Oral stabilizer" } },
  
  // Neuromyelitis Optica
  { id: "ext-neuro-095", name: "Eculizumab (NMOSD)", phase: "Approved", indication: "NMOSD", therapeuticArea: "Neurology/CNS", company: "Alexion", companyTrackRecord: 'fast', nctId: "NCT01892345", scores: calculateProbabilityScores("Approved", "NMOSD", "Neurology"), marketData: generateMarketProjections("Eculizumab NMOSD", "Approved", "NMOSD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "C5 complement inhibitor", administration: "IV every 2 weeks", keyAdvantage: "Relapse prevention" } },
  { id: "ext-neuro-096", name: "Inebilizumab", phase: "Approved", indication: "NMOSD", therapeuticArea: "Neurology/CNS", company: "Horizon/Viela", companyTrackRecord: 'average', nctId: "NCT02200770", scores: calculateProbabilityScores("Approved", "NMOSD", "Neurology"), marketData: generateMarketProjections("Inebilizumab", "Approved", "NMOSD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CD19 antibody", administration: "IV every 6 months", keyAdvantage: "6-month dosing" } },
  { id: "ext-neuro-097", name: "Satralizumab", phase: "Approved", indication: "NMOSD", therapeuticArea: "Neurology/CNS", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT02028884", scores: calculateProbabilityScores("Approved", "NMOSD", "Neurology"), marketData: generateMarketProjections("Satralizumab", "Approved", "NMOSD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-IL-6R antibody", administration: "SC monthly", keyAdvantage: "SC administration" } },
  { id: "ext-neuro-098", name: "Ravulizumab (NMOSD)", phase: "Phase III", indication: "NMOSD", therapeuticArea: "Neurology/CNS", company: "Alexion", companyTrackRecord: 'fast', nctId: "NCT04201262", scores: calculateProbabilityScores("Phase III", "NMOSD", "Neurology"), marketData: generateMarketProjections("Ravulizumab NMOSD", "Phase III", "NMOSD", 'fast'), overallScore: 0, drugInfo: { class: "C5 complement inhibitor", administration: "IV every 8 weeks", keyAdvantage: "Extended dosing" } },
  
  // Angelman Syndrome
  { id: "ext-neuro-099", name: "GTX-102", phase: "Phase I/II", indication: "Angelman Syndrome", therapeuticArea: "Neurology/CNS", company: "Ultragenyx", companyTrackRecord: 'average', nctId: "NCT04259281", scores: calculateProbabilityScores("Phase I", "Angelman Syndrome", "Neurology"), marketData: generateMarketProjections("GTX-102", "Phase I", "Angelman Syndrome", 'average'), overallScore: 0, drugInfo: { class: "Antisense oligonucleotide", administration: "Intrathecal", keyAdvantage: "UBE3A activation" } },
  { id: "ext-neuro-100", name: "STK-001", phase: "Phase I/II", indication: "Dravet Syndrome", therapeuticArea: "Neurology/CNS", company: "Stoke Therapeutics", companyTrackRecord: 'average', nctId: "NCT04442295", scores: calculateProbabilityScores("Phase I", "Epilepsy", "Neurology"), marketData: generateMarketProjections("STK-001", "Phase I", "Epilepsy", 'average'), overallScore: 0, drugInfo: { class: "TANGO ASO", administration: "Intrathecal", keyAdvantage: "SCN1A upregulation" } },
];
