// Extended Oncology Molecules - 100 additional oncology/hematology molecules
import { calculateProbabilityScores, generateMarketProjections } from './scoring';
import { type MoleculeProfile } from './moleculesData';

export const extendedOncologyMolecules: MoleculeProfile[] = [
  // Lung Cancer Additions
  { id: "ext-onc-001", name: "Lazertinib", phase: "Approved", indication: "EGFR+ NSCLC", therapeuticArea: "Oncology/Hematology", company: "Janssen/Yuhan", companyTrackRecord: 'fast', nctId: "NCT04148898", scores: calculateProbabilityScores("Approved", "NSCLC", "Oncology"), marketData: generateMarketProjections("Lazertinib", "Approved", "NSCLC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Third-generation EGFR TKI", administration: "Oral daily", keyAdvantage: "CNS penetration" } },
  { id: "ext-onc-002", name: "Furmonertinib", phase: "Phase III", indication: "EGFR+ NSCLC", therapeuticArea: "Oncology/Hematology", company: "Allist Pharmaceuticals", companyTrackRecord: 'average', nctId: "NCT03787992", scores: calculateProbabilityScores("Phase III", "NSCLC", "Oncology"), marketData: generateMarketProjections("Furmonertinib", "Phase III", "NSCLC", 'average'), overallScore: 0, drugInfo: { class: "EGFR TKI", administration: "Oral", keyAdvantage: "China-focused development" } },
  { id: "ext-onc-003", name: "Sunvozertinib", phase: "Phase III", indication: "EGFR Exon20 NSCLC", therapeuticArea: "Oncology/Hematology", company: "Dizal Pharma", companyTrackRecord: 'average', nctId: "NCT05712902", scores: calculateProbabilityScores("Phase III", "NSCLC", "Oncology"), marketData: generateMarketProjections("Sunvozertinib", "Phase III", "NSCLC", 'average'), overallScore: 0, drugInfo: { class: "EGFR Exon20 inhibitor", administration: "Oral", keyAdvantage: "Exon20 selectivity" } },
  { id: "ext-onc-004", name: "Divarasib", phase: "Phase III", indication: "KRAS G12C NSCLC/CRC", therapeuticArea: "Oncology/Hematology", company: "Genentech", companyTrackRecord: 'fast', nctId: "NCT05578092", scores: calculateProbabilityScores("Phase III", "NSCLC", "Oncology"), marketData: generateMarketProjections("Divarasib", "Phase III", "NSCLC", 'fast'), overallScore: 0, drugInfo: { class: "KRAS G12C inhibitor", administration: "Oral daily", keyAdvantage: "Once-daily dosing" } },
  { id: "ext-onc-005", name: "Garsorasib", phase: "Phase II", indication: "KRAS G12C Solid Tumors", therapeuticArea: "Oncology/Hematology", company: "InventisBio", companyTrackRecord: 'average', nctId: "NCT05002270", scores: calculateProbabilityScores("Phase II", "Solid Tumors", "Oncology"), marketData: generateMarketProjections("Garsorasib", "Phase II", "Solid Tumors", 'average'), overallScore: 0, drugInfo: { class: "KRAS G12C inhibitor", administration: "Oral", keyAdvantage: "China development" } },
  { id: "ext-onc-006", name: "Opnurasib", phase: "Phase II", indication: "KRAS G12D Solid Tumors", therapeuticArea: "Oncology/Hematology", company: "Revolution Medicines", companyTrackRecord: 'average', nctId: "NCT05379985", scores: calculateProbabilityScores("Phase II", "Solid Tumors", "Oncology"), marketData: generateMarketProjections("Opnurasib", "Phase II", "Solid Tumors", 'average'), overallScore: 0, drugInfo: { class: "KRAS G12D inhibitor", administration: "Oral", keyAdvantage: "First G12D inhibitor" } },
  { id: "ext-onc-007", name: "Datopotamab Deruxtecan", phase: "Phase III", indication: "HR+/HER2- Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "AstraZeneca/Daiichi", companyTrackRecord: 'fast', nctId: "NCT05104866", scores: calculateProbabilityScores("Phase III", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Datopotamab Deruxtecan", "Phase III", "Breast Cancer", 'fast'), overallScore: 0, drugInfo: { class: "TROP2-directed ADC", administration: "IV infusion", keyAdvantage: "Deruxtecan payload" } },
  { id: "ext-onc-008", name: "Patritumab Deruxtecan", phase: "Phase III", indication: "HER3+ NSCLC", therapeuticArea: "Oncology/Hematology", company: "Daiichi Sankyo", companyTrackRecord: 'fast', nctId: "NCT05338970", scores: calculateProbabilityScores("Phase III", "NSCLC", "Oncology"), marketData: generateMarketProjections("Patritumab Deruxtecan", "Phase III", "NSCLC", 'fast'), overallScore: 0, drugInfo: { class: "HER3-directed ADC", administration: "IV infusion", keyAdvantage: "HER3 targeting" } },
  { id: "ext-onc-009", name: "Ifinatamab Deruxtecan", phase: "Phase II", indication: "Small Cell Lung Cancer", therapeuticArea: "Oncology/Hematology", company: "Daiichi Sankyo", companyTrackRecord: 'fast', nctId: "NCT05280470", scores: calculateProbabilityScores("Phase II", "SCLC", "Oncology"), marketData: generateMarketProjections("Ifinatamab Deruxtecan", "Phase II", "SCLC", 'fast'), overallScore: 0, drugInfo: { class: "B7-H3-directed ADC", administration: "IV infusion", keyAdvantage: "B7-H3 target in SCLC" } },
  { id: "ext-onc-010", name: "Telisotuzumab Vedotin", phase: "Phase III", indication: "c-Met+ NSCLC", therapeuticArea: "Oncology/Hematology", company: "AbbVie", companyTrackRecord: 'fast', nctId: "NCT04928846", scores: calculateProbabilityScores("Phase III", "NSCLC", "Oncology"), marketData: generateMarketProjections("Telisotuzumab Vedotin", "Phase III", "NSCLC", 'fast'), overallScore: 0, drugInfo: { class: "c-Met-directed ADC", administration: "IV infusion", keyAdvantage: "c-Met overexpression" } },
  
  // Breast Cancer Additions
  { id: "ext-onc-011", name: "Elacestrant", phase: "Approved", indication: "ER+/HER2- Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "Menarini/Stemline", companyTrackRecord: 'average', nctId: "NCT03778931", scores: calculateProbabilityScores("Approved", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Elacestrant", "Approved", "Breast Cancer", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Oral SERD", administration: "Oral daily", keyAdvantage: "Oral administration" } },
  { id: "ext-onc-012", name: "Camizestrant", phase: "Phase III", indication: "ER+/HER2- Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT04711252", scores: calculateProbabilityScores("Phase III", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Camizestrant", "Phase III", "Breast Cancer", 'fast'), overallScore: 0, drugInfo: { class: "Next-gen oral SERD", administration: "Oral", keyAdvantage: "ESR1 mutation coverage" } },
  { id: "ext-onc-013", name: "Imlunestrant", phase: "Phase III", indication: "ER+/HER2- Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT04975308", scores: calculateProbabilityScores("Phase III", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Imlunestrant", "Phase III", "Breast Cancer", 'fast'), overallScore: 0, drugInfo: { class: "Complete ER antagonist", administration: "Oral", keyAdvantage: "Complete ER degradation" } },
  { id: "ext-onc-014", name: "Giredestrant", phase: "Phase III", indication: "ER+/HER2- Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT04546009", scores: calculateProbabilityScores("Phase III", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Giredestrant", "Phase III", "Breast Cancer", 'fast'), overallScore: 0, drugInfo: { class: "Oral SERD", administration: "Oral", keyAdvantage: "Non-steroidal SERD" } },
  { id: "ext-onc-015", name: "Samuraciclib", phase: "Phase II", indication: "HR+ Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "Carrick Therapeutics", companyTrackRecord: 'average', nctId: "NCT05573633", scores: calculateProbabilityScores("Phase II", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Samuraciclib", "Phase II", "Breast Cancer", 'average'), overallScore: 0, drugInfo: { class: "CDK7 inhibitor", administration: "Oral", keyAdvantage: "CDK7 targeting" } },
  { id: "ext-onc-016", name: "Inavolisib", phase: "Phase III", indication: "PIK3CA+ Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT04191499", scores: calculateProbabilityScores("Phase III", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Inavolisib", "Phase III", "Breast Cancer", 'fast'), overallScore: 0, drugInfo: { class: "PI3K inhibitor", administration: "Oral", keyAdvantage: "PI3Kα selectivity" } },
  { id: "ext-onc-017", name: "ARX788", phase: "Phase II", indication: "HER2+ Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "Ambrx/NovaRock", companyTrackRecord: 'average', nctId: "NCT04829604", scores: calculateProbabilityScores("Phase II", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("ARX788", "Phase II", "Breast Cancer", 'average'), overallScore: 0, drugInfo: { class: "HER2 ADC", administration: "IV infusion", keyAdvantage: "Site-specific conjugation" } },
  { id: "ext-onc-018", name: "SYD985", phase: "Phase III", indication: "HER2+ Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "Byondis", companyTrackRecord: 'average', nctId: "NCT03262935", scores: calculateProbabilityScores("Phase III", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("SYD985", "Phase III", "Breast Cancer", 'average'), overallScore: 0, drugInfo: { class: "HER2-targeted duocarmycin ADC", administration: "IV infusion", keyAdvantage: "Duocarmycin payload" } },
  { id: "ext-onc-019", name: "Margetuximab", phase: "Approved", indication: "HER2+ Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "MacroGenics", companyTrackRecord: 'average', nctId: "NCT02492711", scores: calculateProbabilityScores("Approved", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Margetuximab", "Approved", "Breast Cancer", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Fc-optimized anti-HER2", administration: "IV infusion", keyAdvantage: "Enhanced ADCC" } },
  { id: "ext-onc-020", name: "Tucatinib", phase: "Approved", indication: "HER2+ Breast Cancer", therapeuticArea: "Oncology/Hematology", company: "Seagen", companyTrackRecord: 'fast', nctId: "NCT02614794", scores: calculateProbabilityScores("Approved", "Breast Cancer", "Oncology"), marketData: generateMarketProjections("Tucatinib", "Approved", "Breast Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "HER2-selective TKI", administration: "Oral twice daily", keyAdvantage: "CNS activity" } },
  
  // Colorectal Cancer
  { id: "ext-onc-021", name: "Fruquintinib", phase: "Approved", indication: "Metastatic CRC", therapeuticArea: "Oncology/Hematology", company: "Hutchmed/Takeda", companyTrackRecord: 'average', nctId: "NCT04322539", scores: calculateProbabilityScores("Approved", "CRC", "Oncology"), marketData: generateMarketProjections("Fruquintinib", "Approved", "CRC", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "VEGFR inhibitor", administration: "Oral", keyAdvantage: "Highly selective VEGFR 1/2/3" } },
  { id: "ext-onc-022", name: "Tucatinib + Trastuzumab", phase: "Phase III", indication: "HER2+ CRC", therapeuticArea: "Oncology/Hematology", company: "Seagen", companyTrackRecord: 'fast', nctId: "NCT03043313", scores: calculateProbabilityScores("Phase III", "CRC", "Oncology"), marketData: generateMarketProjections("Tucatinib CRC", "Phase III", "CRC", 'fast'), overallScore: 0, drugInfo: { class: "HER2 TKI combo", administration: "Oral + IV", keyAdvantage: "HER2+ CRC option" } },
  { id: "ext-onc-023", name: "Botensilimab", phase: "Phase II", indication: "MSS CRC", therapeuticArea: "Oncology/Hematology", company: "Agenus", companyTrackRecord: 'average', nctId: "NCT03860272", scores: calculateProbabilityScores("Phase II", "CRC", "Oncology"), marketData: generateMarketProjections("Botensilimab", "Phase II", "CRC", 'average'), overallScore: 0, drugInfo: { class: "Fc-enhanced CTLA-4", administration: "IV infusion", keyAdvantage: "MSS CRC activity" } },
  { id: "ext-onc-024", name: "Cetuximab-MMAE", phase: "Phase II", indication: "EGFR+ CRC", therapeuticArea: "Oncology/Hematology", company: "Pfizer", companyTrackRecord: 'fast', nctId: "NCT04663763", scores: calculateProbabilityScores("Phase II", "CRC", "Oncology"), marketData: generateMarketProjections("Cetuximab-MMAE", "Phase II", "CRC", 'fast'), overallScore: 0, drugInfo: { class: "EGFR-directed ADC", administration: "IV infusion", keyAdvantage: "ADC approach to CRC" } },
  { id: "ext-onc-025", name: "Encorafenib/Binimetinib", phase: "Approved", indication: "BRAF V600E CRC", therapeuticArea: "Oncology/Hematology", company: "Pfizer", companyTrackRecord: 'fast', nctId: "NCT02928224", scores: calculateProbabilityScores("Approved", "CRC", "Oncology"), marketData: generateMarketProjections("Encorafenib/Binimetinib", "Approved", "CRC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "BRAF/MEK inhibitor combo", administration: "Oral", keyAdvantage: "BEACON regimen" } },
  
  // Prostate Cancer
  { id: "ext-onc-026", name: "Talazoparib + Enzalutamide", phase: "Approved", indication: "mCRPC", therapeuticArea: "Oncology/Hematology", company: "Pfizer", companyTrackRecord: 'fast', nctId: "NCT03395197", scores: calculateProbabilityScores("Approved", "Prostate Cancer", "Oncology"), marketData: generateMarketProjections("Talazoparib combo", "Approved", "Prostate Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PARP + AR inhibitor", administration: "Oral", keyAdvantage: "HRR+ and HRR- activity" } },
  { id: "ext-onc-027", name: "Niraparib + Abiraterone", phase: "Approved", indication: "mCRPC", therapeuticArea: "Oncology/Hematology", company: "Janssen", companyTrackRecord: 'fast', nctId: "NCT03748641", scores: calculateProbabilityScores("Approved", "Prostate Cancer", "Oncology"), marketData: generateMarketProjections("Niraparib combo", "Approved", "Prostate Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PARP + CYP17 inhibitor", administration: "Oral", keyAdvantage: "BRCA+ benefit" } },
  { id: "ext-onc-028", name: "Pluvicto (Lutetium-177)", phase: "Approved", indication: "PSMA+ mCRPC", therapeuticArea: "Oncology/Hematology", company: "Novartis", companyTrackRecord: 'fast', nctId: "NCT03511664", scores: calculateProbabilityScores("Approved", "Prostate Cancer", "Oncology"), marketData: generateMarketProjections("Pluvicto", "Approved", "Prostate Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PSMA radioligand therapy", administration: "IV infusion", keyAdvantage: "Targeted radiotherapy" } },
  { id: "ext-onc-029", name: "ARV-110", phase: "Phase II", indication: "mCRPC", therapeuticArea: "Oncology/Hematology", company: "Arvinas", companyTrackRecord: 'average', nctId: "NCT03888612", scores: calculateProbabilityScores("Phase II", "Prostate Cancer", "Oncology"), marketData: generateMarketProjections("ARV-110", "Phase II", "Prostate Cancer", 'average'), overallScore: 0, drugInfo: { class: "AR PROTAC degrader", administration: "Oral", keyAdvantage: "Novel degradation mechanism" } },
  { id: "ext-onc-030", name: "Apalutamide", phase: "Approved", indication: "Non-metastatic CRPC", therapeuticArea: "Oncology/Hematology", company: "Janssen", companyTrackRecord: 'fast', nctId: "NCT01946204", scores: calculateProbabilityScores("Approved", "Prostate Cancer", "Oncology"), marketData: generateMarketProjections("Apalutamide", "Approved", "Prostate Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "AR antagonist", administration: "Oral daily", keyAdvantage: "High AR binding affinity" } },
  
  // Hematologic Malignancies
  { id: "ext-onc-031", name: "Venetoclax", phase: "Approved", indication: "CLL/AML", therapeuticArea: "Oncology/Hematology", company: "AbbVie/Roche", companyTrackRecord: 'fast', nctId: "NCT02756611", scores: calculateProbabilityScores("Approved", "CLL", "Oncology"), marketData: generateMarketProjections("Venetoclax", "Approved", "CLL", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "BCL-2 inhibitor", administration: "Oral daily", keyAdvantage: "First BCL-2 inhibitor" } },
  { id: "ext-onc-032", name: "Pirtobrutinib", phase: "Approved", indication: "CLL/MCL", therapeuticArea: "Oncology/Hematology", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT03740529", scores: calculateProbabilityScores("Approved", "CLL", "Oncology"), marketData: generateMarketProjections("Pirtobrutinib", "Approved", "CLL", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Non-covalent BTK inhibitor", administration: "Oral", keyAdvantage: "Active after covalent BTKi" } },
  { id: "ext-onc-033", name: "Sonrotoclax", phase: "Phase II", indication: "CLL", therapeuticArea: "Oncology/Hematology", company: "AbbVie", companyTrackRecord: 'fast', nctId: "NCT04982302", scores: calculateProbabilityScores("Phase II", "CLL", "Oncology"), marketData: generateMarketProjections("Sonrotoclax", "Phase II", "CLL", 'fast'), overallScore: 0, drugInfo: { class: "Next-gen BCL-2 inhibitor", administration: "Oral", keyAdvantage: "Improved therapeutic window" } },
  { id: "ext-onc-034", name: "Nemtabrutinib", phase: "Phase II", indication: "CLL", therapeuticArea: "Oncology/Hematology", company: "Merck", companyTrackRecord: 'fast', nctId: "NCT03162536", scores: calculateProbabilityScores("Phase II", "CLL", "Oncology"), marketData: generateMarketProjections("Nemtabrutinib", "Phase II", "CLL", 'fast'), overallScore: 0, drugInfo: { class: "Non-covalent BTKi", administration: "Oral", keyAdvantage: "Resistance coverage" } },
  { id: "ext-onc-035", name: "Lisocabtagene Maraleucel", phase: "Approved", indication: "DLBCL", therapeuticArea: "Oncology/Hematology", company: "BMS", companyTrackRecord: 'fast', nctId: "NCT02631044", scores: calculateProbabilityScores("Approved", "DLBCL", "Oncology"), marketData: generateMarketProjections("Lisocabtagene Maraleucel", "Approved", "DLBCL", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CD19 CAR-T", administration: "Single IV infusion", keyAdvantage: "4-1BB costimulatory domain" } },
  { id: "ext-onc-036", name: "Brexucabtagene Autoleucel", phase: "Approved", indication: "ALL", therapeuticArea: "Oncology/Hematology", company: "Kite/Gilead", companyTrackRecord: 'fast', nctId: "NCT02614066", scores: calculateProbabilityScores("Approved", "ALL", "Oncology"), marketData: generateMarketProjections("Brexucabtagene Autoleucel", "Approved", "ALL", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CD19 CAR-T", administration: "Single IV infusion", keyAdvantage: "Adult ALL indication" } },
  { id: "ext-onc-037", name: "Idecabtagene Vicleucel", phase: "Approved", indication: "Multiple Myeloma", therapeuticArea: "Oncology/Hematology", company: "BMS/bluebird", companyTrackRecord: 'fast', nctId: "NCT03361748", scores: calculateProbabilityScores("Approved", "Multiple Myeloma", "Oncology"), marketData: generateMarketProjections("Idecabtagene Vicleucel", "Approved", "Multiple Myeloma", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "BCMA CAR-T", administration: "Single IV infusion", keyAdvantage: "First BCMA CAR-T" } },
  { id: "ext-onc-038", name: "Ciltacabtagene Autoleucel", phase: "Approved", indication: "Multiple Myeloma", therapeuticArea: "Oncology/Hematology", company: "Janssen/Legend", companyTrackRecord: 'fast', nctId: "NCT03548207", scores: calculateProbabilityScores("Approved", "Multiple Myeloma", "Oncology"), marketData: generateMarketProjections("Ciltacabtagene Autoleucel", "Approved", "Multiple Myeloma", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "BCMA CAR-T", administration: "Single IV infusion", keyAdvantage: "Dual epitope binding" } },
  { id: "ext-onc-039", name: "Linvoseltamab", phase: "Phase III", indication: "Multiple Myeloma", therapeuticArea: "Oncology/Hematology", company: "Regeneron", companyTrackRecord: 'fast', nctId: "NCT05020236", scores: calculateProbabilityScores("Phase III", "Multiple Myeloma", "Oncology"), marketData: generateMarketProjections("Linvoseltamab", "Phase III", "Multiple Myeloma", 'fast'), overallScore: 0, drugInfo: { class: "BCMA bispecific", administration: "SC weekly", keyAdvantage: "VeloCI-T platform" } },
  { id: "ext-onc-040", name: "Talquetamab", phase: "Approved", indication: "Multiple Myeloma", therapeuticArea: "Oncology/Hematology", company: "Janssen", companyTrackRecord: 'fast', nctId: "NCT03399799", scores: calculateProbabilityScores("Approved", "Multiple Myeloma", "Oncology"), marketData: generateMarketProjections("Talquetamab", "Approved", "Multiple Myeloma", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "GPRC5D bispecific", administration: "SC", keyAdvantage: "Novel GPRC5D target" } },
  
  // Leukemia Additional
  { id: "ext-onc-041", name: "Gilteritinib", phase: "Approved", indication: "FLT3+ AML", therapeuticArea: "Oncology/Hematology", company: "Astellas", companyTrackRecord: 'fast', nctId: "NCT02421939", scores: calculateProbabilityScores("Approved", "AML", "Oncology"), marketData: generateMarketProjections("Gilteritinib", "Approved", "AML", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "FLT3 inhibitor", administration: "Oral daily", keyAdvantage: "FLT3 ITD and TKD coverage" } },
  { id: "ext-onc-042", name: "Menin Inhibitors (SNDX-5613)", phase: "Phase II", indication: "KMT2A AML/ALL", therapeuticArea: "Oncology/Hematology", company: "Syndax", companyTrackRecord: 'average', nctId: "NCT04065399", scores: calculateProbabilityScores("Phase II", "AML", "Oncology"), marketData: generateMarketProjections("SNDX-5613", "Phase II", "AML", 'average'), overallScore: 0, drugInfo: { class: "Menin inhibitor", administration: "Oral", keyAdvantage: "KMT2A-rearranged targeting" } },
  { id: "ext-onc-043", name: "Quizartinib", phase: "Approved", indication: "FLT3-ITD AML", therapeuticArea: "Oncology/Hematology", company: "Daiichi Sankyo", companyTrackRecord: 'fast', nctId: "NCT02668653", scores: calculateProbabilityScores("Approved", "AML", "Oncology"), marketData: generateMarketProjections("Quizartinib", "Approved", "AML", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "FLT3-ITD inhibitor", administration: "Oral", keyAdvantage: "ITD selectivity" } },
  { id: "ext-onc-044", name: "Ivosidenib", phase: "Approved", indication: "IDH1+ AML", therapeuticArea: "Oncology/Hematology", company: "Servier", companyTrackRecord: 'average', nctId: "NCT02074839", scores: calculateProbabilityScores("Approved", "AML", "Oncology"), marketData: generateMarketProjections("Ivosidenib", "Approved", "AML", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "IDH1 inhibitor", administration: "Oral", keyAdvantage: "IDH1 mutation targeting" } },
  { id: "ext-onc-045", name: "Enasidenib", phase: "Approved", indication: "IDH2+ AML", therapeuticArea: "Oncology/Hematology", company: "BMS", companyTrackRecord: 'fast', nctId: "NCT01915498", scores: calculateProbabilityScores("Approved", "AML", "Oncology"), marketData: generateMarketProjections("Enasidenib", "Approved", "AML", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "IDH2 inhibitor", administration: "Oral", keyAdvantage: "First IDH2 inhibitor" } },
  
  // Lymphoma Additional
  { id: "ext-onc-046", name: "Polatuzumab Vedotin", phase: "Approved", indication: "DLBCL", therapeuticArea: "Oncology/Hematology", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT02257567", scores: calculateProbabilityScores("Approved", "DLBCL", "Oncology"), marketData: generateMarketProjections("Polatuzumab Vedotin", "Approved", "DLBCL", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CD79b-directed ADC", administration: "IV infusion", keyAdvantage: "Pola-R-CHP standard" } },
  { id: "ext-onc-047", name: "Loncastuximab Tesirine", phase: "Approved", indication: "DLBCL", therapeuticArea: "Oncology/Hematology", company: "ADC Therapeutics", companyTrackRecord: 'average', nctId: "NCT02669017", scores: calculateProbabilityScores("Approved", "DLBCL", "Oncology"), marketData: generateMarketProjections("Loncastuximab Tesirine", "Approved", "DLBCL", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CD19-directed ADC", administration: "IV infusion", keyAdvantage: "PBD dimer payload" } },
  { id: "ext-onc-048", name: "Tafasitamab + Lenalidomide", phase: "Approved", indication: "DLBCL", therapeuticArea: "Oncology/Hematology", company: "Morphosys/Incyte", companyTrackRecord: 'average', nctId: "NCT02399085", scores: calculateProbabilityScores("Approved", "DLBCL", "Oncology"), marketData: generateMarketProjections("Tafasitamab", "Approved", "DLBCL", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Fc-enhanced CD19", administration: "IV + oral", keyAdvantage: "Chemo-free option" } },
  { id: "ext-onc-049", name: "Brentuximab Vedotin", phase: "Approved", indication: "Hodgkin Lymphoma", therapeuticArea: "Oncology/Hematology", company: "Seagen", companyTrackRecord: 'fast', nctId: "NCT01712490", scores: calculateProbabilityScores("Approved", "Hodgkin Lymphoma", "Oncology"), marketData: generateMarketProjections("Brentuximab Vedotin", "Approved", "Hodgkin Lymphoma", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CD30-directed ADC", administration: "IV infusion", keyAdvantage: "CD30 targeting" } },
  { id: "ext-onc-050", name: "Nivolumab (Lymphoma)", phase: "Approved", indication: "Hodgkin Lymphoma", therapeuticArea: "Oncology/Hematology", company: "BMS", companyTrackRecord: 'fast', nctId: "NCT02181738", scores: calculateProbabilityScores("Approved", "Hodgkin Lymphoma", "Oncology"), marketData: generateMarketProjections("Nivolumab HL", "Approved", "Hodgkin Lymphoma", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-PD-1", administration: "IV infusion", keyAdvantage: "Post-ASCT indication" } },
  
  // Melanoma and Skin Cancer
  { id: "ext-onc-051", name: "Relatlimab + Nivolumab", phase: "Approved", indication: "Melanoma", therapeuticArea: "Oncology/Hematology", company: "BMS", companyTrackRecord: 'fast', nctId: "NCT03470922", scores: calculateProbabilityScores("Approved", "Melanoma", "Oncology"), marketData: generateMarketProjections("Relatlimab combo", "Approved", "Melanoma", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "LAG-3 + PD-1", administration: "IV infusion", keyAdvantage: "First LAG-3 inhibitor" } },
  { id: "ext-onc-052", name: "Lifileucel", phase: "Approved", indication: "Melanoma", therapeuticArea: "Oncology/Hematology", company: "Iovance", companyTrackRecord: 'average', nctId: "NCT02360579", scores: calculateProbabilityScores("Approved", "Melanoma", "Oncology"), marketData: generateMarketProjections("Lifileucel", "Approved", "Melanoma", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TIL therapy", administration: "Single IV infusion", keyAdvantage: "First TIL therapy" } },
  { id: "ext-onc-053", name: "Cemiplimab", phase: "Approved", indication: "Cutaneous SCC", therapeuticArea: "Oncology/Hematology", company: "Regeneron/Sanofi", companyTrackRecord: 'fast', nctId: "NCT02760498", scores: calculateProbabilityScores("Approved", "Skin Cancer", "Oncology"), marketData: generateMarketProjections("Cemiplimab", "Approved", "Skin Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-PD-1", administration: "IV infusion", keyAdvantage: "CSCC first approval" } },
  { id: "ext-onc-054", name: "Tebentafusp", phase: "Approved", indication: "Uveal Melanoma", therapeuticArea: "Oncology/Hematology", company: "Immunocore", companyTrackRecord: 'average', nctId: "NCT03070392", scores: calculateProbabilityScores("Approved", "Melanoma", "Oncology"), marketData: generateMarketProjections("Tebentafusp", "Approved", "Melanoma", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "gp100 x CD3 bispecific", administration: "IV infusion", keyAdvantage: "First therapy for uveal melanoma" } },
  { id: "ext-onc-055", name: "Fianlimab + Cemiplimab", phase: "Phase III", indication: "Melanoma", therapeuticArea: "Oncology/Hematology", company: "Regeneron", companyTrackRecord: 'fast', nctId: "NCT05352672", scores: calculateProbabilityScores("Phase III", "Melanoma", "Oncology"), marketData: generateMarketProjections("Fianlimab combo", "Phase III", "Melanoma", 'fast'), overallScore: 0, drugInfo: { class: "LAG-3 + PD-1", administration: "IV infusion", keyAdvantage: "LAG-3 combination" } },
  
  // GI Cancers
  { id: "ext-onc-056", name: "Zolbetuximab", phase: "Approved", indication: "CLDN18.2+ Gastric Cancer", therapeuticArea: "Oncology/Hematology", company: "Astellas", companyTrackRecord: 'fast', nctId: "NCT03504397", scores: calculateProbabilityScores("Approved", "Gastric Cancer", "Oncology"), marketData: generateMarketProjections("Zolbetuximab", "Approved", "Gastric Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CLDN18.2", administration: "IV infusion", keyAdvantage: "First CLDN18.2 therapy" } },
  { id: "ext-onc-057", name: "Tislelizumab", phase: "Approved", indication: "Esophageal Cancer", therapeuticArea: "Oncology/Hematology", company: "BeiGene/Novartis", companyTrackRecord: 'average', nctId: "NCT03430843", scores: calculateProbabilityScores("Approved", "Esophageal Cancer", "Oncology"), marketData: generateMarketProjections("Tislelizumab", "Approved", "Esophageal Cancer", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-PD-1", administration: "IV infusion", keyAdvantage: "Engineered Fc region" } },
  { id: "ext-onc-058", name: "Durvalumab + Tremelimumab", phase: "Approved", indication: "Hepatocellular Carcinoma", therapeuticArea: "Oncology/Hematology", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT03298451", scores: calculateProbabilityScores("Approved", "HCC", "Oncology"), marketData: generateMarketProjections("STRIDE regimen", "Approved", "HCC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PD-L1 + CTLA-4", administration: "IV infusion", keyAdvantage: "STRIDE dosing regimen" } },
  { id: "ext-onc-059", name: "Tremelimumab", phase: "Approved", indication: "HCC", therapeuticArea: "Oncology/Hematology", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT03298451", scores: calculateProbabilityScores("Approved", "HCC", "Oncology"), marketData: generateMarketProjections("Tremelimumab", "Approved", "HCC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CTLA-4", administration: "IV single dose", keyAdvantage: "Single priming dose" } },
  { id: "ext-onc-060", name: "Ramucirumab", phase: "Approved", indication: "Gastric/GEJ Cancer", therapeuticArea: "Oncology/Hematology", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT00917384", scores: calculateProbabilityScores("Approved", "Gastric Cancer", "Oncology"), marketData: generateMarketProjections("Ramucirumab", "Approved", "Gastric Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-VEGFR2", administration: "IV infusion", keyAdvantage: "VEGFR2 specific" } },
  
  // Pancreatic Cancer
  { id: "ext-onc-061", name: "Olaparib (Pancreatic)", phase: "Approved", indication: "BRCA+ Pancreatic Cancer", therapeuticArea: "Oncology/Hematology", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT02184195", scores: calculateProbabilityScores("Approved", "Pancreatic Cancer", "Oncology"), marketData: generateMarketProjections("Olaparib PDAC", "Approved", "Pancreatic Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PARP inhibitor", administration: "Oral", keyAdvantage: "gBRCA maintenance" } },
  { id: "ext-onc-062", name: "ELI-002 2P", phase: "Phase I/II", indication: "KRAS+ Pancreatic/CRC", therapeuticArea: "Oncology/Hematology", company: "Elicio Therapeutics", companyTrackRecord: 'average', nctId: "NCT04853017", scores: calculateProbabilityScores("Phase I", "Pancreatic Cancer", "Oncology"), marketData: generateMarketProjections("ELI-002", "Phase I", "Pancreatic Cancer", 'average'), overallScore: 0, drugInfo: { class: "Amphiphile KRAS vaccine", administration: "SC injection", keyAdvantage: "mKRAS immunotherapy" } },
  { id: "ext-onc-063", name: "Pamrevlumab", phase: "Phase III", indication: "Pancreatic Cancer", therapeuticArea: "Oncology/Hematology", company: "FibroGen", companyTrackRecord: 'average', nctId: "NCT03941093", scores: calculateProbabilityScores("Phase III", "Pancreatic Cancer", "Oncology"), marketData: generateMarketProjections("Pamrevlumab", "Phase III", "Pancreatic Cancer", 'average'), overallScore: 0, drugInfo: { class: "Anti-CTGF", administration: "IV infusion", keyAdvantage: "Stroma targeting" } },
  
  // Ovarian Cancer
  { id: "ext-onc-064", name: "Mirvetuximab Soravtansine", phase: "Approved", indication: "FRα+ Ovarian Cancer", therapeuticArea: "Oncology/Hematology", company: "ImmunoGen", companyTrackRecord: 'average', nctId: "NCT04209855", scores: calculateProbabilityScores("Approved", "Ovarian Cancer", "Oncology"), marketData: generateMarketProjections("Mirvetuximab Soravtansine", "Approved", "Ovarian Cancer", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "FRα-directed ADC", administration: "IV infusion", keyAdvantage: "FRα high expression" } },
  { id: "ext-onc-065", name: "Rucaparib", phase: "Approved", indication: "BRCA+ Ovarian Cancer", therapeuticArea: "Oncology/Hematology", company: "Clovis", companyTrackRecord: 'average', nctId: "NCT01891344", scores: calculateProbabilityScores("Approved", "Ovarian Cancer", "Oncology"), marketData: generateMarketProjections("Rucaparib", "Approved", "Ovarian Cancer", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PARP inhibitor", administration: "Oral twice daily", keyAdvantage: "BRCA and HRD" } },
  { id: "ext-onc-066", name: "Niraparib", phase: "Approved", indication: "Ovarian Cancer Maintenance", therapeuticArea: "Oncology/Hematology", company: "GSK", companyTrackRecord: 'fast', nctId: "NCT01847274", scores: calculateProbabilityScores("Approved", "Ovarian Cancer", "Oncology"), marketData: generateMarketProjections("Niraparib", "Approved", "Ovarian Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PARP inhibitor", administration: "Oral daily", keyAdvantage: "All-comer maintenance" } },
  { id: "ext-onc-067", name: "Lurbinectedin", phase: "Approved", indication: "SCLC/Ovarian", therapeuticArea: "Oncology/Hematology", company: "Jazz/PharmaMar", companyTrackRecord: 'average', nctId: "NCT02454972", scores: calculateProbabilityScores("Approved", "SCLC", "Oncology"), marketData: generateMarketProjections("Lurbinectedin", "Approved", "SCLC", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "RNA polymerase II inhibitor", administration: "IV infusion", keyAdvantage: "Novel mechanism" } },
  
  // Kidney/RCC
  { id: "ext-onc-068", name: "Belzutifan", phase: "Approved", indication: "VHL-associated RCC", therapeuticArea: "Oncology/Hematology", company: "Merck", companyTrackRecord: 'fast', nctId: "NCT03401788", scores: calculateProbabilityScores("Approved", "RCC", "Oncology"), marketData: generateMarketProjections("Belzutifan", "Approved", "RCC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "HIF-2α inhibitor", administration: "Oral daily", keyAdvantage: "First HIF-2α inhibitor" } },
  { id: "ext-onc-069", name: "Cabozantinib + Nivolumab", phase: "Approved", indication: "Advanced RCC", therapeuticArea: "Oncology/Hematology", company: "Exelixis/BMS", companyTrackRecord: 'fast', nctId: "NCT03141177", scores: calculateProbabilityScores("Approved", "RCC", "Oncology"), marketData: generateMarketProjections("Cabo-Nivo", "Approved", "RCC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TKI + PD-1", administration: "Oral + IV", keyAdvantage: "CheckMate 9ER regimen" } },
  { id: "ext-onc-070", name: "Lenvatinib + Pembrolizumab", phase: "Approved", indication: "Advanced RCC", therapeuticArea: "Oncology/Hematology", company: "Eisai/Merck", companyTrackRecord: 'fast', nctId: "NCT02811861", scores: calculateProbabilityScores("Approved", "RCC", "Oncology"), marketData: generateMarketProjections("Lenva-Pembro", "Approved", "RCC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TKI + PD-1", administration: "Oral + IV", keyAdvantage: "CLEAR regimen" } },
  
  // Head and Neck Cancer
  { id: "ext-onc-071", name: "Pembrolizumab (HNSCC)", phase: "Approved", indication: "Head and Neck SCC", therapeuticArea: "Oncology/Hematology", company: "Merck", companyTrackRecord: 'fast', nctId: "NCT02358031", scores: calculateProbabilityScores("Approved", "HNSCC", "Oncology"), marketData: generateMarketProjections("Pembro HNSCC", "Approved", "HNSCC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-PD-1", administration: "IV infusion", keyAdvantage: "First-line HNSCC" } },
  { id: "ext-onc-072", name: "Xevinapant", phase: "Phase III", indication: "Locally Advanced HNSCC", therapeuticArea: "Oncology/Hematology", company: "Merck KGaA", companyTrackRecord: 'average', nctId: "NCT04459715", scores: calculateProbabilityScores("Phase III", "HNSCC", "Oncology"), marketData: generateMarketProjections("Xevinapant", "Phase III", "HNSCC", 'average'), overallScore: 0, drugInfo: { class: "IAP antagonist", administration: "IV infusion", keyAdvantage: "Chemoradiation combo" } },
  
  // Bladder/Urothelial
  { id: "ext-onc-073", name: "Enfortumab Vedotin", phase: "Approved", indication: "Urothelial Carcinoma", therapeuticArea: "Oncology/Hematology", company: "Seagen/Astellas", companyTrackRecord: 'fast', nctId: "NCT03474107", scores: calculateProbabilityScores("Approved", "Bladder Cancer", "Oncology"), marketData: generateMarketProjections("Enfortumab Vedotin", "Approved", "Bladder Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Nectin-4 ADC", administration: "IV infusion", keyAdvantage: "EV-302 landmark" } },
  { id: "ext-onc-074", name: "Erdafitinib", phase: "Approved", indication: "FGFR+ Urothelial Cancer", therapeuticArea: "Oncology/Hematology", company: "Janssen", companyTrackRecord: 'fast', nctId: "NCT02365597", scores: calculateProbabilityScores("Approved", "Bladder Cancer", "Oncology"), marketData: generateMarketProjections("Erdafitinib", "Approved", "Bladder Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "FGFR inhibitor", administration: "Oral", keyAdvantage: "First FGFR in UC" } },
  { id: "ext-onc-075", name: "Sacituzumab Govitecan (UC)", phase: "Approved", indication: "Metastatic UC", therapeuticArea: "Oncology/Hematology", company: "Gilead", companyTrackRecord: 'fast', nctId: "NCT03547973", scores: calculateProbabilityScores("Approved", "Bladder Cancer", "Oncology"), marketData: generateMarketProjections("SG UC", "Approved", "Bladder Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TROP2 ADC", administration: "IV infusion", keyAdvantage: "TROPiCS-04 data" } },
  
  // Sarcoma
  { id: "ext-onc-076", name: "Tazemetostat", phase: "Approved", indication: "Epithelioid Sarcoma", therapeuticArea: "Oncology/Hematology", company: "Epizyme/Ipsen", companyTrackRecord: 'average', nctId: "NCT02601950", scores: calculateProbabilityScores("Approved", "Sarcoma", "Oncology"), marketData: generateMarketProjections("Tazemetostat", "Approved", "Sarcoma", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "EZH2 inhibitor", administration: "Oral", keyAdvantage: "First EZH2 approval" } },
  { id: "ext-onc-077", name: "Avapritinib", phase: "Approved", indication: "PDGFRA Exon 18 GIST", therapeuticArea: "Oncology/Hematology", company: "Blueprint", companyTrackRecord: 'average', nctId: "NCT02508532", scores: calculateProbabilityScores("Approved", "GIST", "Oncology"), marketData: generateMarketProjections("Avapritinib", "Approved", "GIST", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "KIT/PDGFRα inhibitor", administration: "Oral", keyAdvantage: "D842V mutation" } },
  { id: "ext-onc-078", name: "Ripretinib", phase: "Approved", indication: "Advanced GIST", therapeuticArea: "Oncology/Hematology", company: "Deciphera", companyTrackRecord: 'average', nctId: "NCT03353753", scores: calculateProbabilityScores("Approved", "GIST", "Oncology"), marketData: generateMarketProjections("Ripretinib", "Approved", "GIST", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Switch-control KIT inhibitor", administration: "Oral", keyAdvantage: "Broad mutation coverage" } },
  
  // Thyroid Cancer
  { id: "ext-onc-079", name: "Selpercatinib", phase: "Approved", indication: "RET+ Thyroid Cancer", therapeuticArea: "Oncology/Hematology", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT03157128", scores: calculateProbabilityScores("Approved", "Thyroid Cancer", "Oncology"), marketData: generateMarketProjections("Selpercatinib", "Approved", "Thyroid Cancer", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "RET inhibitor", administration: "Oral", keyAdvantage: "High CNS penetration" } },
  { id: "ext-onc-080", name: "Pralsetinib", phase: "Approved", indication: "RET+ Thyroid/NSCLC", therapeuticArea: "Oncology/Hematology", company: "Blueprint/Roche", companyTrackRecord: 'average', nctId: "NCT03037385", scores: calculateProbabilityScores("Approved", "Thyroid Cancer", "Oncology"), marketData: generateMarketProjections("Pralsetinib", "Approved", "Thyroid Cancer", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "RET inhibitor", administration: "Oral", keyAdvantage: "Once-daily dosing" } },
  { id: "ext-onc-081", name: "Larotrectinib", phase: "Approved", indication: "NTRK+ Solid Tumors", therapeuticArea: "Oncology/Hematology", company: "Bayer", companyTrackRecord: 'fast', nctId: "NCT02576431", scores: calculateProbabilityScores("Approved", "Solid Tumors", "Oncology"), marketData: generateMarketProjections("Larotrectinib", "Approved", "Solid Tumors", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TRK inhibitor", administration: "Oral", keyAdvantage: "Tumor-agnostic approval" } },
  { id: "ext-onc-082", name: "Entrectinib", phase: "Approved", indication: "NTRK+/ROS1+ Tumors", therapeuticArea: "Oncology/Hematology", company: "Roche", companyTrackRecord: 'fast', nctId: "NCT02568267", scores: calculateProbabilityScores("Approved", "Solid Tumors", "Oncology"), marketData: generateMarketProjections("Entrectinib", "Approved", "Solid Tumors", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TRK/ROS1/ALK inhibitor", administration: "Oral", keyAdvantage: "CNS activity" } },
  
  // Brain Tumors
  { id: "ext-onc-083", name: "Vorasidenib", phase: "Approved", indication: "Low-Grade Glioma", therapeuticArea: "Oncology/Hematology", company: "Servier", companyTrackRecord: 'average', nctId: "NCT04164901", scores: calculateProbabilityScores("Approved", "Glioma", "Oncology"), marketData: generateMarketProjections("Vorasidenib", "Approved", "Glioma", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Dual IDH1/2 inhibitor", administration: "Oral", keyAdvantage: "Brain-penetrant" } },
  { id: "ext-onc-084", name: "ONC201", phase: "Phase III", indication: "H3 K27M Glioma", therapeuticArea: "Oncology/Hematology", company: "Chimerix", companyTrackRecord: 'average', nctId: "NCT05580562", scores: calculateProbabilityScores("Phase III", "Glioma", "Oncology"), marketData: generateMarketProjections("ONC201", "Phase III", "Glioma", 'average'), overallScore: 0, drugInfo: { class: "DRD2 antagonist/ClpP agonist", administration: "Oral weekly", keyAdvantage: "H3 K27M targeting" } },
  { id: "ext-onc-085", name: "Tovorafenib", phase: "Approved", indication: "Pediatric Low-Grade Glioma", therapeuticArea: "Oncology/Hematology", company: "Day One Biopharmaceuticals", companyTrackRecord: 'average', nctId: "NCT04775485", scores: calculateProbabilityScores("Approved", "Pediatric Glioma", "Oncology"), marketData: generateMarketProjections("Tovorafenib", "Approved", "Pediatric Glioma", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "RAF inhibitor", administration: "Oral weekly", keyAdvantage: "Weekly pediatric dosing" } },
  
  // Mesothelioma
  { id: "ext-onc-086", name: "Nivolumab + Ipilimumab (Meso)", phase: "Approved", indication: "Malignant Mesothelioma", therapeuticArea: "Oncology/Hematology", company: "BMS", companyTrackRecord: 'fast', nctId: "NCT02899299", scores: calculateProbabilityScores("Approved", "Mesothelioma", "Oncology"), marketData: generateMarketProjections("Nivo-Ipi Meso", "Approved", "Mesothelioma", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PD-1 + CTLA-4", administration: "IV infusion", keyAdvantage: "First immunotherapy for meso" } },
  
  // Bile Duct/Cholangiocarcinoma
  { id: "ext-onc-087", name: "Pemigatinib", phase: "Approved", indication: "FGFR2+ Cholangiocarcinoma", therapeuticArea: "Oncology/Hematology", company: "Incyte", companyTrackRecord: 'average', nctId: "NCT02924376", scores: calculateProbabilityScores("Approved", "Cholangiocarcinoma", "Oncology"), marketData: generateMarketProjections("Pemigatinib", "Approved", "Cholangiocarcinoma", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "FGFR1-3 inhibitor", administration: "Oral", keyAdvantage: "First CCA-specific approval" } },
  { id: "ext-onc-088", name: "Futibatinib", phase: "Approved", indication: "FGFR2+ Cholangiocarcinoma", therapeuticArea: "Oncology/Hematology", company: "Taiho", companyTrackRecord: 'average', nctId: "NCT02052778", scores: calculateProbabilityScores("Approved", "Cholangiocarcinoma", "Oncology"), marketData: generateMarketProjections("Futibatinib", "Approved", "Cholangiocarcinoma", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Irreversible FGFR inhibitor", administration: "Oral", keyAdvantage: "Covalent binding" } },
  { id: "ext-onc-089", name: "Durvalumab (BTC)", phase: "Approved", indication: "Biliary Tract Cancer", therapeuticArea: "Oncology/Hematology", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT03875235", scores: calculateProbabilityScores("Approved", "BTC", "Oncology"), marketData: generateMarketProjections("Durvalumab BTC", "Approved", "BTC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-PD-L1", administration: "IV infusion", keyAdvantage: "TOPAZ-1 landmark" } },
  
  // Bispecifics and Novel Modalities
  { id: "ext-onc-090", name: "Epcoritamab", phase: "Approved", indication: "DLBCL", therapeuticArea: "Oncology/Hematology", company: "Genmab/AbbVie", companyTrackRecord: 'fast', nctId: "NCT03625037", scores: calculateProbabilityScores("Approved", "DLBCL", "Oncology"), marketData: generateMarketProjections("Epcoritamab", "Approved", "DLBCL", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "CD20xCD3 bispecific", administration: "SC injection", keyAdvantage: "SC administration" } },
  { id: "ext-onc-091", name: "Odronextamab", phase: "Phase III", indication: "Follicular Lymphoma", therapeuticArea: "Oncology/Hematology", company: "Regeneron", companyTrackRecord: 'fast', nctId: "NCT03888105", scores: calculateProbabilityScores("Phase III", "Follicular Lymphoma", "Oncology"), marketData: generateMarketProjections("Odronextamab", "Phase III", "Follicular Lymphoma", 'fast'), overallScore: 0, drugInfo: { class: "CD20xCD3 bispecific", administration: "IV infusion", keyAdvantage: "High ORR in FL" } },
  { id: "ext-onc-092", name: "Amivantamab", phase: "Approved", indication: "EGFR Exon20 NSCLC", therapeuticArea: "Oncology/Hematology", company: "Janssen", companyTrackRecord: 'fast', nctId: "NCT02609776", scores: calculateProbabilityScores("Approved", "NSCLC", "Oncology"), marketData: generateMarketProjections("Amivantamab", "Approved", "NSCLC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "EGFR-MET bispecific", administration: "IV infusion", keyAdvantage: "First Exon20 therapy" } },
  { id: "ext-onc-093", name: "Zenocutuzumab", phase: "Phase II", indication: "NRG1+ Cancers", therapeuticArea: "Oncology/Hematology", company: "Merus", companyTrackRecord: 'average', nctId: "NCT02912949", scores: calculateProbabilityScores("Phase II", "Solid Tumors", "Oncology"), marketData: generateMarketProjections("Zenocutuzumab", "Phase II", "Solid Tumors", 'average'), overallScore: 0, drugInfo: { class: "HER2xHER3 bispecific", administration: "IV infusion", keyAdvantage: "NRG1 fusion targeting" } },
  
  // Radiopharmaceuticals
  { id: "ext-onc-094", name: "Lu-177 DOTATATE", phase: "Approved", indication: "GEP-NETs", therapeuticArea: "Oncology/Hematology", company: "Novartis", companyTrackRecord: 'fast', nctId: "NCT01578239", scores: calculateProbabilityScores("Approved", "NETs", "Oncology"), marketData: generateMarketProjections("Lutathera", "Approved", "NETs", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Peptide receptor radionuclide therapy", administration: "IV infusion", keyAdvantage: "NETTER-1 landmark" } },
  { id: "ext-onc-095", name: "I-131 omburtamab", phase: "Phase III", indication: "Neuroblastoma", therapeuticArea: "Oncology/Hematology", company: "Y-mAbs", companyTrackRecord: 'average', nctId: "NCT03275402", scores: calculateProbabilityScores("Phase III", "Neuroblastoma", "Oncology"), marketData: generateMarketProjections("I-131 omburtamab", "Phase III", "Neuroblastoma", 'average'), overallScore: 0, drugInfo: { class: "Radioimmunotherapy", administration: "IV infusion", keyAdvantage: "CNS compartment" } },
  
  // Novel Mechanisms
  { id: "ext-onc-096", name: "Berzosertib", phase: "Phase II", indication: "Platinum-Resistant Ovarian", therapeuticArea: "Oncology/Hematology", company: "Merck KGaA", companyTrackRecord: 'average', nctId: "NCT02567409", scores: calculateProbabilityScores("Phase II", "Ovarian Cancer", "Oncology"), marketData: generateMarketProjections("Berzosertib", "Phase II", "Ovarian Cancer", 'average'), overallScore: 0, drugInfo: { class: "ATR inhibitor", administration: "IV infusion", keyAdvantage: "DNA damage response" } },
  { id: "ext-onc-097", name: "Domatinostat", phase: "Phase II", indication: "Merkel Cell Carcinoma", therapeuticArea: "Oncology/Hematology", company: "4SC", companyTrackRecord: 'average', nctId: "NCT04393753", scores: calculateProbabilityScores("Phase II", "Skin Cancer", "Oncology"), marketData: generateMarketProjections("Domatinostat", "Phase II", "Skin Cancer", 'average'), overallScore: 0, drugInfo: { class: "HDAC inhibitor", administration: "Oral", keyAdvantage: "Epigenetic modulation" } },
  { id: "ext-onc-098", name: "Selinexor", phase: "Approved", indication: "Multiple Myeloma/DLBCL", therapeuticArea: "Oncology/Hematology", company: "Karyopharm", companyTrackRecord: 'average', nctId: "NCT02336815", scores: calculateProbabilityScores("Approved", "Multiple Myeloma", "Oncology"), marketData: generateMarketProjections("Selinexor", "Approved", "Multiple Myeloma", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "XPO1 inhibitor", administration: "Oral", keyAdvantage: "Novel nuclear export" } },
  { id: "ext-onc-099", name: "Adagrasib", phase: "Approved", indication: "KRAS G12C NSCLC", therapeuticArea: "Oncology/Hematology", company: "Mirati/BMS", companyTrackRecord: 'average', nctId: "NCT03785249", scores: calculateProbabilityScores("Approved", "NSCLC", "Oncology"), marketData: generateMarketProjections("Adagrasib", "Approved", "NSCLC", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "KRAS G12C inhibitor", administration: "Oral", keyAdvantage: "Longer half-life" } },
  { id: "ext-onc-100", name: "Mobocertinib", phase: "Phase III", indication: "EGFR Exon20 NSCLC", therapeuticArea: "Oncology/Hematology", company: "Takeda", companyTrackRecord: 'fast', nctId: "NCT02716116", scores: calculateProbabilityScores("Phase III", "NSCLC", "Oncology"), marketData: generateMarketProjections("Mobocertinib", "Phase III", "NSCLC", 'fast'), overallScore: 0, drugInfo: { class: "EGFR Exon20 TKI", administration: "Oral", keyAdvantage: "Oral Exon20 option" } },
];
