// Extended Cardiometabolic Molecules - 100 additional cardiovascular/metabolic molecules
import { calculateProbabilityScores, generateMarketProjections } from './scoring';
import { type MoleculeProfile } from './moleculesData';

export const extendedCardiometabolicMolecules: MoleculeProfile[] = [
  // GLP-1/Obesity
  { id: "ext-cm-001", name: "Semaglutide (Wegovy/Ozempic)", phase: "Approved", indication: "Obesity/Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Novo Nordisk", companyTrackRecord: 'fast', nctId: "NCT03548935", scores: calculateProbabilityScores("Approved", "Obesity", "Metabolic"), marketData: generateMarketProjections("Semaglutide", "Approved", "Obesity", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "GLP-1 receptor agonist", administration: "SC weekly or oral daily", keyAdvantage: "15-17% weight loss" } },
  { id: "ext-cm-002", name: "Tirzepatide (Mounjaro/Zepbound)", phase: "Approved", indication: "Obesity/Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT04184622", scores: calculateProbabilityScores("Approved", "Obesity", "Metabolic"), marketData: generateMarketProjections("Tirzepatide", "Approved", "Obesity", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "GIP/GLP-1 dual agonist", administration: "SC weekly", keyAdvantage: "20-22% weight loss" } },
  { id: "ext-cm-003", name: "Retatrutide", phase: "Phase III", indication: "Obesity/Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT05929066", scores: calculateProbabilityScores("Phase III", "Obesity", "Metabolic"), marketData: generateMarketProjections("Retatrutide", "Phase III", "Obesity", 'fast'), overallScore: 0, drugInfo: { class: "GIP/GLP-1/Glucagon triple agonist", administration: "SC weekly", keyAdvantage: "24% weight loss potential" } },
  { id: "ext-cm-004", name: "Orforglipron", phase: "Phase III", indication: "Obesity/Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT05869903", scores: calculateProbabilityScores("Phase III", "Obesity", "Metabolic"), marketData: generateMarketProjections("Orforglipron", "Phase III", "Obesity", 'fast'), overallScore: 0, drugInfo: { class: "Oral GLP-1 agonist", administration: "Oral daily", keyAdvantage: "Non-peptide oral" } },
  { id: "ext-cm-005", name: "CagriSema", phase: "Phase III", indication: "Obesity/Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Novo Nordisk", companyTrackRecord: 'fast', nctId: "NCT05394519", scores: calculateProbabilityScores("Phase III", "Obesity", "Metabolic"), marketData: generateMarketProjections("CagriSema", "Phase III", "Obesity", 'fast'), overallScore: 0, drugInfo: { class: "Semaglutide + cagrilintide", administration: "SC weekly", keyAdvantage: "GLP-1 + amylin combo" } },
  { id: "ext-cm-006", name: "Survodutide", phase: "Phase III", indication: "Obesity/MASH", therapeuticArea: "Endocrinology & Metabolism", company: "Boehringer Ingelheim", companyTrackRecord: 'fast', nctId: "NCT04667377", scores: calculateProbabilityScores("Phase III", "Obesity", "Metabolic"), marketData: generateMarketProjections("Survodutide", "Phase III", "Obesity", 'fast'), overallScore: 0, drugInfo: { class: "GLP-1/Glucagon dual agonist", administration: "SC weekly", keyAdvantage: "MASH efficacy" } },
  { id: "ext-cm-007", name: "Pemvidutide", phase: "Phase II", indication: "Obesity/MASH", therapeuticArea: "Endocrinology & Metabolism", company: "Altimmune", companyTrackRecord: 'average', nctId: "NCT05295875", scores: calculateProbabilityScores("Phase II", "Obesity", "Metabolic"), marketData: generateMarketProjections("Pemvidutide", "Phase II", "Obesity", 'average'), overallScore: 0, drugInfo: { class: "GLP-1/Glucagon dual agonist", administration: "SC weekly", keyAdvantage: "Liver-directed" } },
  { id: "ext-cm-008", name: "Mazdutide", phase: "Phase III", indication: "Obesity/Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Innovent Biologics", companyTrackRecord: 'average', nctId: "NCT05607680", scores: calculateProbabilityScores("Phase III", "Obesity", "Metabolic"), marketData: generateMarketProjections("Mazdutide", "Phase III", "Obesity", 'average'), overallScore: 0, drugInfo: { class: "GLP-1/Glucagon dual agonist", administration: "SC", keyAdvantage: "China-focused" } },
  { id: "ext-cm-009", name: "Danuglipron", phase: "Phase II", indication: "Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Pfizer", companyTrackRecord: 'fast', nctId: "NCT05127551", scores: calculateProbabilityScores("Phase II", "Diabetes", "Metabolic"), marketData: generateMarketProjections("Danuglipron", "Phase II", "Diabetes", 'fast'), overallScore: 0, drugInfo: { class: "Oral GLP-1 agonist", administration: "Oral twice daily", keyAdvantage: "Small molecule oral" } },
  { id: "ext-cm-010", name: "Cotadutide", phase: "Phase II", indication: "MASH/Obesity", therapeuticArea: "Endocrinology & Metabolism", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT04019561", scores: calculateProbabilityScores("Phase II", "MASH", "Metabolic"), marketData: generateMarketProjections("Cotadutide", "Phase II", "MASH", 'fast'), overallScore: 0, drugInfo: { class: "GLP-1/Glucagon dual agonist", administration: "SC", keyAdvantage: "Dual mechanism" } },
  
  // MASH/NAFLD
  { id: "ext-cm-011", name: "Resmetirom", phase: "Approved", indication: "MASH with Fibrosis", therapeuticArea: "Gastroenterology & Hepatology", company: "Madrigal", companyTrackRecord: 'average', nctId: "NCT03900429", scores: calculateProbabilityScores("Approved", "MASH", "Metabolic"), marketData: generateMarketProjections("Resmetirom", "Approved", "MASH", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "THR-β agonist", administration: "Oral daily", keyAdvantage: "First MASH approval" } },
  { id: "ext-cm-012", name: "Efruxifermin", phase: "Phase III", indication: "MASH", therapeuticArea: "Gastroenterology & Hepatology", company: "Akero Therapeutics", companyTrackRecord: 'average', nctId: "NCT06161194", scores: calculateProbabilityScores("Phase III", "MASH", "Metabolic"), marketData: generateMarketProjections("Efruxifermin", "Phase III", "MASH", 'average'), overallScore: 0, drugInfo: { class: "FGF21 analog", administration: "SC weekly", keyAdvantage: "40% fibrosis improvement" } },
  { id: "ext-cm-013", name: "Pegozafermin", phase: "Phase III", indication: "MASH/Severe Hypertriglyceridemia", therapeuticArea: "Gastroenterology & Hepatology", company: "89bio", companyTrackRecord: 'average', nctId: "NCT06153095", scores: calculateProbabilityScores("Phase III", "MASH", "Metabolic"), marketData: generateMarketProjections("Pegozafermin", "Phase III", "MASH", 'average'), overallScore: 0, drugInfo: { class: "PEG-FGF21", administration: "SC weekly", keyAdvantage: "Extended half-life" } },
  { id: "ext-cm-014", name: "Lanifibranor", phase: "Phase III", indication: "MASH", therapeuticArea: "Gastroenterology & Hepatology", company: "Inventiva", companyTrackRecord: 'average', nctId: "NCT04849728", scores: calculateProbabilityScores("Phase III", "MASH", "Metabolic"), marketData: generateMarketProjections("Lanifibranor", "Phase III", "MASH", 'average'), overallScore: 0, drugInfo: { class: "Pan-PPAR agonist", administration: "Oral daily", keyAdvantage: "Triple PPAR activation" } },
  { id: "ext-cm-015", name: "Obeticholic Acid", phase: "Phase III", indication: "MASH/PBC", therapeuticArea: "Gastroenterology & Hepatology", company: "Intercept", companyTrackRecord: 'average', nctId: "NCT02548351", scores: calculateProbabilityScores("Phase III", "MASH", "Metabolic"), marketData: generateMarketProjections("Obeticholic Acid", "Phase III", "MASH", 'average'), overallScore: 0, drugInfo: { class: "FXR agonist", administration: "Oral daily", keyAdvantage: "Bile acid receptor" } },
  { id: "ext-cm-016", name: "Aldafermin", phase: "Phase II", indication: "MASH", therapeuticArea: "Gastroenterology & Hepatology", company: "NGM Bio", companyTrackRecord: 'average', nctId: "NCT03912532", scores: calculateProbabilityScores("Phase II", "MASH", "Metabolic"), marketData: generateMarketProjections("Aldafermin", "Phase II", "MASH", 'average'), overallScore: 0, drugInfo: { class: "FGF19 analog", administration: "SC", keyAdvantage: "FGF19 pathway" } },
  { id: "ext-cm-017", name: "Firsocostat", phase: "Phase II", indication: "MASH", therapeuticArea: "Gastroenterology & Hepatology", company: "Gilead", companyTrackRecord: 'fast', nctId: "NCT03449446", scores: calculateProbabilityScores("Phase II", "MASH", "Metabolic"), marketData: generateMarketProjections("Firsocostat", "Phase II", "MASH", 'fast'), overallScore: 0, drugInfo: { class: "ACC inhibitor", administration: "Oral", keyAdvantage: "DNL inhibition" } },
  { id: "ext-cm-018", name: "Selonsertib", phase: "Phase III", indication: "MASH", therapeuticArea: "Gastroenterology & Hepatology", company: "Gilead", companyTrackRecord: 'fast', nctId: "NCT03053050", scores: calculateProbabilityScores("Phase III", "MASH", "Metabolic"), marketData: generateMarketProjections("Selonsertib", "Phase III", "MASH", 'fast'), overallScore: 0, isFailed: true, drugInfo: { class: "ASK1 inhibitor", administration: "Oral", keyAdvantage: "ASK1 pathway" } },
  { id: "ext-cm-019", name: "Denifanstat", phase: "Phase II", indication: "MASH", therapeuticArea: "Gastroenterology & Hepatology", company: "Sagimet", companyTrackRecord: 'average', nctId: "NCT04906421", scores: calculateProbabilityScores("Phase II", "MASH", "Metabolic"), marketData: generateMarketProjections("Denifanstat", "Phase II", "MASH", 'average'), overallScore: 0, drugInfo: { class: "FASN inhibitor", administration: "Oral", keyAdvantage: "Fatty acid synthesis" } },
  { id: "ext-cm-020", name: "Icosabutate", phase: "Phase II", indication: "MASH", therapeuticArea: "Gastroenterology & Hepatology", company: "NorthSea Therapeutics", companyTrackRecord: 'average', nctId: "NCT04052516", scores: calculateProbabilityScores("Phase II", "MASH", "Metabolic"), marketData: generateMarketProjections("Icosabutate", "Phase II", "MASH", 'average'), overallScore: 0, drugInfo: { class: "Structured EPA analog", administration: "Oral", keyAdvantage: "Lipid/inflammation" } },
  
  // Heart Failure
  { id: "ext-cm-021", name: "Dapagliflozin (Heart Failure)", phase: "Approved", indication: "HFrEF/HFpEF", therapeuticArea: "Cardiovascular", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT03619213", scores: calculateProbabilityScores("Approved", "Heart Failure", "Cardiology"), marketData: generateMarketProjections("Dapagliflozin HF", "Approved", "Heart Failure", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "SGLT2 inhibitor", administration: "Oral daily", keyAdvantage: "HFpEF indication" } },
  { id: "ext-cm-022", name: "Empagliflozin (Heart Failure)", phase: "Approved", indication: "HFrEF/HFpEF", therapeuticArea: "Cardiovascular", company: "Boehringer/Lilly", companyTrackRecord: 'fast', nctId: "NCT03057977", scores: calculateProbabilityScores("Approved", "Heart Failure", "Cardiology"), marketData: generateMarketProjections("Empagliflozin HF", "Approved", "Heart Failure", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "SGLT2 inhibitor", administration: "Oral daily", keyAdvantage: "EMPEROR trials" } },
  { id: "ext-cm-023", name: "Sotagliflozin", phase: "Approved", indication: "Heart Failure + Diabetes", therapeuticArea: "Cardiovascular", company: "Lexicon", companyTrackRecord: 'average', nctId: "NCT03315143", scores: calculateProbabilityScores("Approved", "Heart Failure", "Cardiology"), marketData: generateMarketProjections("Sotagliflozin", "Approved", "Heart Failure", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "SGLT1/2 dual inhibitor", administration: "Oral daily", keyAdvantage: "Dual SGLT inhibition" } },
  { id: "ext-cm-024", name: "Omecamtiv Mecarbil", phase: "Phase III/NDA Pending", indication: "HFrEF", therapeuticArea: "Cardiovascular", company: "Cytokinetics/Amgen", companyTrackRecord: 'average', nctId: "NCT02929329", scores: calculateProbabilityScores("Phase III", "Heart Failure", "Cardiology"), marketData: generateMarketProjections("Omecamtiv Mecarbil", "Phase III", "Heart Failure", 'average'), overallScore: 0, drugInfo: { class: "Cardiac myosin activator", administration: "Oral twice daily", keyAdvantage: "Novel mechanism" } },
  { id: "ext-cm-025", name: "Aficamten", phase: "Phase III", indication: "Obstructive HCM", therapeuticArea: "Cardiovascular", company: "Cytokinetics", companyTrackRecord: 'average', nctId: "NCT05186818", scores: calculateProbabilityScores("Phase III", "HCM", "Cardiology"), marketData: generateMarketProjections("Aficamten", "Phase III", "HCM", 'average'), overallScore: 0, drugInfo: { class: "Cardiac myosin inhibitor", administration: "Oral daily", keyAdvantage: "HCM treatment" } },
  { id: "ext-cm-026", name: "Mavacamten", phase: "Approved", indication: "Obstructive HCM", therapeuticArea: "Cardiovascular", company: "BMS", companyTrackRecord: 'fast', nctId: "NCT03470545", scores: calculateProbabilityScores("Approved", "HCM", "Cardiology"), marketData: generateMarketProjections("Mavacamten", "Approved", "HCM", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Cardiac myosin inhibitor", administration: "Oral daily", keyAdvantage: "First HCM therapy" } },
  { id: "ext-cm-027", name: "Vericiguat", phase: "Approved", indication: "Worsening HFrEF", therapeuticArea: "Cardiovascular", company: "Merck/Bayer", companyTrackRecord: 'fast', nctId: "NCT02861534", scores: calculateProbabilityScores("Approved", "Heart Failure", "Cardiology"), marketData: generateMarketProjections("Vericiguat", "Approved", "Heart Failure", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "sGC stimulator", administration: "Oral daily", keyAdvantage: "Worsening HF indication" } },
  { id: "ext-cm-028", name: "Zilebesiran", phase: "Phase II", indication: "Hypertension", therapeuticArea: "Cardiovascular", company: "Alnylam", companyTrackRecord: 'fast', nctId: "NCT05103332", scores: calculateProbabilityScores("Phase II", "Hypertension", "Cardiology"), marketData: generateMarketProjections("Zilebesiran", "Phase II", "Hypertension", 'fast'), overallScore: 0, drugInfo: { class: "RNAi targeting AGT", administration: "SC every 6 months", keyAdvantage: "Biannual dosing" } },
  { id: "ext-cm-029", name: "Lorundrostat", phase: "Phase II", indication: "Resistant Hypertension", therapeuticArea: "Cardiovascular", company: "Mineralys", companyTrackRecord: 'average', nctId: "NCT05182840", scores: calculateProbabilityScores("Phase II", "Hypertension", "Cardiology"), marketData: generateMarketProjections("Lorundrostat", "Phase II", "Hypertension", 'average'), overallScore: 0, drugInfo: { class: "Aldosterone synthase inhibitor", administration: "Oral daily", keyAdvantage: "ASI for resistant HTN" } },
  { id: "ext-cm-030", name: "Baxdrostat", phase: "Phase II", indication: "Resistant Hypertension", therapeuticArea: "Cardiovascular", company: "CinCor", companyTrackRecord: 'average', nctId: "NCT04519658", scores: calculateProbabilityScores("Phase II", "Hypertension", "Cardiology"), marketData: generateMarketProjections("Baxdrostat", "Phase II", "Hypertension", 'average'), overallScore: 0, drugInfo: { class: "Aldosterone synthase inhibitor", administration: "Oral", keyAdvantage: "Aldosterone lowering" } },
  
  // Lipid Disorders
  { id: "ext-cm-031", name: "Inclisiran", phase: "Approved", indication: "Hypercholesterolemia", therapeuticArea: "Cardiovascular", company: "Novartis", companyTrackRecord: 'fast', nctId: "NCT03399370", scores: calculateProbabilityScores("Approved", "Hypercholesterolemia", "Cardiology"), marketData: generateMarketProjections("Inclisiran", "Approved", "Hypercholesterolemia", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "siRNA targeting PCSK9", administration: "SC every 6 months", keyAdvantage: "Biannual dosing" } },
  { id: "ext-cm-032", name: "Evolocumab", phase: "Approved", indication: "Hypercholesterolemia/ASCVD", therapeuticArea: "Cardiovascular", company: "Amgen", companyTrackRecord: 'fast', nctId: "NCT01764633", scores: calculateProbabilityScores("Approved", "ASCVD", "Cardiology"), marketData: generateMarketProjections("Evolocumab", "Approved", "ASCVD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-PCSK9 antibody", administration: "SC every 2 weeks", keyAdvantage: "FOURIER outcomes" } },
  { id: "ext-cm-033", name: "Alirocumab", phase: "Approved", indication: "Hypercholesterolemia/ASCVD", therapeuticArea: "Cardiovascular", company: "Regeneron/Sanofi", companyTrackRecord: 'fast', nctId: "NCT01663402", scores: calculateProbabilityScores("Approved", "ASCVD", "Cardiology"), marketData: generateMarketProjections("Alirocumab", "Approved", "ASCVD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-PCSK9 antibody", administration: "SC every 2-4 weeks", keyAdvantage: "ODYSSEY outcomes" } },
  { id: "ext-cm-034", name: "Bempedoic Acid", phase: "Approved", indication: "Hypercholesterolemia", therapeuticArea: "Cardiovascular", company: "Esperion", companyTrackRecord: 'average', nctId: "NCT02988115", scores: calculateProbabilityScores("Approved", "Hypercholesterolemia", "Cardiology"), marketData: generateMarketProjections("Bempedoic Acid", "Approved", "Hypercholesterolemia", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "ACL inhibitor", administration: "Oral daily", keyAdvantage: "Statin intolerant patients" } },
  { id: "ext-cm-035", name: "Evinacumab", phase: "Approved", indication: "Homozygous FH", therapeuticArea: "Cardiovascular", company: "Regeneron", companyTrackRecord: 'fast', nctId: "NCT03399786", scores: calculateProbabilityScores("Approved", "FH", "Cardiology"), marketData: generateMarketProjections("Evinacumab", "Approved", "FH", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-ANGPTL3 antibody", administration: "IV monthly", keyAdvantage: "HoFH indication" } },
  { id: "ext-cm-036", name: "Volanesorsen", phase: "Approved", indication: "FCS (hypertriglyceridemia)", therapeuticArea: "Cardiovascular", company: "Ionis/Akcea", companyTrackRecord: 'fast', nctId: "NCT02211209", scores: calculateProbabilityScores("Approved", "Hypertriglyceridemia", "Cardiology"), marketData: generateMarketProjections("Volanesorsen", "Approved", "Hypertriglyceridemia", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Antisense targeting APOC3", administration: "SC weekly", keyAdvantage: "FCS treatment" } },
  { id: "ext-cm-037", name: "Olpasiran", phase: "Phase III", indication: "Elevated Lp(a)", therapeuticArea: "Cardiovascular", company: "Amgen", companyTrackRecord: 'fast', nctId: "NCT05581303", scores: calculateProbabilityScores("Phase III", "Lp(a)", "Cardiology"), marketData: generateMarketProjections("Olpasiran", "Phase III", "Lp(a)", 'fast'), overallScore: 0, drugInfo: { class: "siRNA targeting LPA", administration: "SC every 12 weeks", keyAdvantage: ">95% Lp(a) reduction" } },
  { id: "ext-cm-038", name: "Pelacarsen", phase: "Phase III", indication: "Elevated Lp(a) + ASCVD", therapeuticArea: "Cardiovascular", company: "Novartis/Ionis", companyTrackRecord: 'fast', nctId: "NCT04023552", scores: calculateProbabilityScores("Phase III", "Lp(a)", "Cardiology"), marketData: generateMarketProjections("Pelacarsen", "Phase III", "Lp(a)", 'fast'), overallScore: 0, drugInfo: { class: "Antisense targeting LPA", administration: "SC monthly", keyAdvantage: "CVOT endpoint" } },
  { id: "ext-cm-039", name: "Lepodisiran", phase: "Phase II", indication: "Elevated Lp(a)", therapeuticArea: "Cardiovascular", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT05565742", scores: calculateProbabilityScores("Phase II", "Lp(a)", "Cardiology"), marketData: generateMarketProjections("Lepodisiran", "Phase II", "Lp(a)", 'fast'), overallScore: 0, drugInfo: { class: "siRNA targeting LPA", administration: "SC biannually", keyAdvantage: "6-month dosing" } },
  { id: "ext-cm-040", name: "Obicetrapib", phase: "Phase III", indication: "Hypercholesterolemia", therapeuticArea: "Cardiovascular", company: "NewAmsterdam", companyTrackRecord: 'average', nctId: "NCT05142722", scores: calculateProbabilityScores("Phase III", "Hypercholesterolemia", "Cardiology"), marketData: generateMarketProjections("Obicetrapib", "Phase III", "Hypercholesterolemia", 'average'), overallScore: 0, drugInfo: { class: "CETP inhibitor", administration: "Oral daily", keyAdvantage: "Low-dose CETP inhibition" } },
  
  // Diabetes
  { id: "ext-cm-041", name: "Insulin Icodec", phase: "Phase III", indication: "Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Novo Nordisk", companyTrackRecord: 'fast', nctId: "NCT04795531", scores: calculateProbabilityScores("Phase III", "Diabetes", "Metabolic"), marketData: generateMarketProjections("Insulin Icodec", "Phase III", "Diabetes", 'fast'), overallScore: 0, drugInfo: { class: "Ultra-long-acting insulin", administration: "SC weekly", keyAdvantage: "Once-weekly basal insulin" } },
  { id: "ext-cm-042", name: "Efsitora alfa", phase: "Phase III", indication: "Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Eli Lilly", companyTrackRecord: 'fast', nctId: "NCT05415566", scores: calculateProbabilityScores("Phase III", "Diabetes", "Metabolic"), marketData: generateMarketProjections("Efsitora alfa", "Phase III", "Diabetes", 'fast'), overallScore: 0, drugInfo: { class: "Weekly basal insulin Fc", administration: "SC weekly", keyAdvantage: "Insulin-Fc technology" } },
  { id: "ext-cm-043", name: "Bexagliflozin", phase: "Approved", indication: "Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "TheracosBio", companyTrackRecord: 'average', nctId: "NCT02558296", scores: calculateProbabilityScores("Approved", "Diabetes", "Metabolic"), marketData: generateMarketProjections("Bexagliflozin", "Approved", "Diabetes", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "SGLT2 inhibitor", administration: "Oral daily", keyAdvantage: "Additional SGLT2i option" } },
  { id: "ext-cm-044", name: "Imeglimin", phase: "Approved (Japan)", indication: "Type 2 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Sumitomo/Poxel", companyTrackRecord: 'average', nctId: "NCT03510091", scores: calculateProbabilityScores("Approved", "Diabetes", "Metabolic"), marketData: generateMarketProjections("Imeglimin", "Approved", "Diabetes", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Mitochondrial bioenergetic", administration: "Oral twice daily", keyAdvantage: "Novel mechanism" } },
  { id: "ext-cm-045", name: "Donislecel (Lantidra)", phase: "Approved", indication: "Type 1 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "CellTrans", companyTrackRecord: 'average', nctId: "NCT00014911", scores: calculateProbabilityScores("Approved", "Type 1 Diabetes", "Metabolic"), marketData: generateMarketProjections("Donislecel", "Approved", "Type 1 Diabetes", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Allogeneic islet cell therapy", administration: "Hepatic infusion", keyAdvantage: "First cell therapy for T1D" } },
  { id: "ext-cm-046", name: "Teplizumab", phase: "Approved", indication: "Stage 2 Type 1 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Provention Bio/Sanofi", companyTrackRecord: 'average', nctId: "NCT01030861", scores: calculateProbabilityScores("Approved", "Type 1 Diabetes", "Metabolic"), marketData: generateMarketProjections("Teplizumab", "Approved", "Type 1 Diabetes", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-CD3 antibody", administration: "IV daily x 14 days", keyAdvantage: "T1D delay therapy" } },
  { id: "ext-cm-047", name: "VX-880", phase: "Phase I/II", indication: "Type 1 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Vertex", companyTrackRecord: 'fast', nctId: "NCT04786262", scores: calculateProbabilityScores("Phase I", "Type 1 Diabetes", "Metabolic"), marketData: generateMarketProjections("VX-880", "Phase I", "Type 1 Diabetes", 'fast'), overallScore: 0, drugInfo: { class: "Stem cell-derived islets", administration: "Hepatic infusion", keyAdvantage: "Insulin independence" } },
  { id: "ext-cm-048", name: "VX-264", phase: "Phase I/II", indication: "Type 1 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Vertex", companyTrackRecord: 'fast', nctId: "NCT05791201", scores: calculateProbabilityScores("Phase I", "Type 1 Diabetes", "Metabolic"), marketData: generateMarketProjections("VX-264", "Phase I", "Type 1 Diabetes", 'fast'), overallScore: 0, drugInfo: { class: "Encapsulated islet cells", administration: "SC implant", keyAdvantage: "No immunosuppression" } },
  { id: "ext-cm-049", name: "Golimumab (T1D)", phase: "Phase II", indication: "New-onset Type 1 Diabetes", therapeuticArea: "Endocrinology & Metabolism", company: "Janssen", companyTrackRecord: 'fast', nctId: "NCT02846545", scores: calculateProbabilityScores("Phase II", "Type 1 Diabetes", "Metabolic"), marketData: generateMarketProjections("Golimumab T1D", "Phase II", "Type 1 Diabetes", 'fast'), overallScore: 0, drugInfo: { class: "Anti-TNF antibody", administration: "SC", keyAdvantage: "C-peptide preservation" } },
  { id: "ext-cm-050", name: "Cotadutide (Diabetes)", phase: "Phase II", indication: "Type 2 Diabetes + Obesity", therapeuticArea: "Endocrinology & Metabolism", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT03235050", scores: calculateProbabilityScores("Phase II", "Diabetes", "Metabolic"), marketData: generateMarketProjections("Cotadutide DM", "Phase II", "Diabetes", 'fast'), overallScore: 0, drugInfo: { class: "GLP-1/Glucagon dual agonist", administration: "SC", keyAdvantage: "Glycemic + weight" } },
  
  // Pulmonary Arterial Hypertension
  { id: "ext-cm-051", name: "Sotatercept", phase: "Approved", indication: "Pulmonary Arterial Hypertension", therapeuticArea: "Cardiovascular", company: "Merck", companyTrackRecord: 'fast', nctId: "NCT04576988", scores: calculateProbabilityScores("Approved", "PAH", "Cardiology"), marketData: generateMarketProjections("Sotatercept", "Approved", "PAH", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "ActRIIA-Fc fusion", administration: "SC every 3 weeks", keyAdvantage: "First-in-class disease modifier" } },
  { id: "ext-cm-052", name: "Ralinepag", phase: "Phase III", indication: "Pulmonary Arterial Hypertension", therapeuticArea: "Cardiovascular", company: "United Therapeutics", companyTrackRecord: 'average', nctId: "NCT03626688", scores: calculateProbabilityScores("Phase III", "PAH", "Cardiology"), marketData: generateMarketProjections("Ralinepag", "Phase III", "PAH", 'average'), overallScore: 0, drugInfo: { class: "Oral IP receptor agonist", administration: "Oral twice daily", keyAdvantage: "Oral prostacyclin" } },
  { id: "ext-cm-053", name: "Treprostinil (implantable)", phase: "Approved", indication: "Pulmonary Arterial Hypertension", therapeuticArea: "Cardiovascular", company: "United Therapeutics", companyTrackRecord: 'average', nctId: "NCT02270632", scores: calculateProbabilityScores("Approved", "PAH", "Cardiology"), marketData: generateMarketProjections("Treprostinil Implant", "Approved", "PAH", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Prostacyclin analog", administration: "SC implantable pump", keyAdvantage: "Continuous SC delivery" } },
  { id: "ext-cm-054", name: "Treprostinil Palmitil", phase: "Phase III", indication: "PAH", therapeuticArea: "Cardiovascular", company: "United Therapeutics", companyTrackRecord: 'average', nctId: "NCT03416205", scores: calculateProbabilityScores("Phase III", "PAH", "Cardiology"), marketData: generateMarketProjections("Treprostinil Palmitil", "Phase III", "PAH", 'average'), overallScore: 0, drugInfo: { class: "Inhaled prostacyclin prodrug", administration: "Inhaled", keyAdvantage: "Sustained-release inhaled" } },
  { id: "ext-cm-055", name: "Riociguat", phase: "Approved", indication: "PAH/CTEPH", therapeuticArea: "Cardiovascular", company: "Bayer", companyTrackRecord: 'fast', nctId: "NCT00810693", scores: calculateProbabilityScores("Approved", "PAH", "Cardiology"), marketData: generateMarketProjections("Riociguat", "Approved", "PAH", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "sGC stimulator", administration: "Oral three times daily", keyAdvantage: "CTEPH indication" } },
  
  // Atherosclerosis/Inflammation
  { id: "ext-cm-056", name: "Canakinumab", phase: "Approved", indication: "ASCVD (Inflammatory)", therapeuticArea: "Cardiovascular", company: "Novartis", companyTrackRecord: 'fast', nctId: "NCT01327846", scores: calculateProbabilityScores("Approved", "ASCVD", "Cardiology"), marketData: generateMarketProjections("Canakinumab CV", "Approved", "ASCVD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-IL-1β antibody", administration: "SC every 3 months", keyAdvantage: "CANTOS inflammatory CV" } },
  { id: "ext-cm-057", name: "Colchicine (LoDoCo)", phase: "Approved", indication: "ASCVD", therapeuticArea: "Cardiovascular", company: "Agepha", companyTrackRecord: 'average', nctId: "NCT02898610", scores: calculateProbabilityScores("Approved", "ASCVD", "Cardiology"), marketData: generateMarketProjections("Colchicine CV", "Approved", "ASCVD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Anti-inflammatory", administration: "Oral daily", keyAdvantage: "Low-cost CV protection" } },
  { id: "ext-cm-058", name: "Ziltivekimab", phase: "Phase III", indication: "ASCVD + Chronic Inflammation", therapeuticArea: "Cardiovascular", company: "Novo Nordisk", companyTrackRecord: 'fast', nctId: "NCT05021835", scores: calculateProbabilityScores("Phase III", "ASCVD", "Cardiology"), marketData: generateMarketProjections("Ziltivekimab", "Phase III", "ASCVD", 'fast'), overallScore: 0, drugInfo: { class: "Anti-IL-6 antibody", administration: "SC monthly", keyAdvantage: "IL-6 reduction in CKD" } },
  
  // Cardiomyopathy
  { id: "ext-cm-059", name: "Tafamidis (Cardiomyopathy)", phase: "Approved", indication: "ATTR-CM", therapeuticArea: "Cardiovascular", company: "Pfizer", companyTrackRecord: 'fast', nctId: "NCT01994889", scores: calculateProbabilityScores("Approved", "Cardiomyopathy", "Cardiology"), marketData: generateMarketProjections("Tafamidis CM", "Approved", "Cardiomyopathy", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TTR stabilizer", administration: "Oral daily", keyAdvantage: "ATTR-CM approval" } },
  { id: "ext-cm-060", name: "Acoramidis", phase: "Approved", indication: "ATTR-CM", therapeuticArea: "Cardiovascular", company: "BridgeBio", companyTrackRecord: 'average', nctId: "NCT03860935", scores: calculateProbabilityScores("Approved", "Cardiomyopathy", "Cardiology"), marketData: generateMarketProjections("Acoramidis", "Approved", "Cardiomyopathy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "TTR stabilizer", administration: "Oral twice daily", keyAdvantage: "Near-complete stabilization" } },
  { id: "ext-cm-061", name: "Patisiran (CM)", phase: "Phase III", indication: "ATTR-CM", therapeuticArea: "Cardiovascular", company: "Alnylam", companyTrackRecord: 'fast', nctId: "NCT03997383", scores: calculateProbabilityScores("Phase III", "Cardiomyopathy", "Cardiology"), marketData: generateMarketProjections("Patisiran CM", "Phase III", "Cardiomyopathy", 'fast'), overallScore: 0, drugInfo: { class: "RNAi therapeutic", administration: "IV every 3 weeks", keyAdvantage: "TTR knockdown" } },
  { id: "ext-cm-062", name: "Eplontersen (CM)", phase: "Phase III", indication: "ATTR-CM", therapeuticArea: "Cardiovascular", company: "Ionis/AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT04302220", scores: calculateProbabilityScores("Phase III", "Cardiomyopathy", "Cardiology"), marketData: generateMarketProjections("Eplontersen CM", "Phase III", "Cardiomyopathy", 'fast'), overallScore: 0, drugInfo: { class: "Ligand-conjugated ASO", administration: "SC monthly", keyAdvantage: "Monthly SC ASO" } },
  
  // Arrhythmias
  { id: "ext-cm-063", name: "Celivarone", phase: "Phase III", indication: "Atrial Fibrillation", therapeuticArea: "Cardiovascular", company: "Sanofi", companyTrackRecord: 'fast', nctId: "NCT01061567", scores: calculateProbabilityScores("Phase III", "AF", "Cardiology"), marketData: generateMarketProjections("Celivarone", "Phase III", "AF", 'fast'), overallScore: 0, drugInfo: { class: "Multi-ion channel blocker", administration: "Oral", keyAdvantage: "Mixed channel block" } },
  { id: "ext-cm-064", name: "Etripamil", phase: "Phase III", indication: "PSVT Termination", therapeuticArea: "Cardiovascular", company: "Milestone", companyTrackRecord: 'average', nctId: "NCT03464019", scores: calculateProbabilityScores("Phase III", "Arrhythmia", "Cardiology"), marketData: generateMarketProjections("Etripamil", "Phase III", "Arrhythmia", 'average'), overallScore: 0, drugInfo: { class: "Calcium channel blocker", administration: "Nasal spray", keyAdvantage: "Self-administered nasal" } },
  
  // CKD
  { id: "ext-cm-065", name: "Finerenone", phase: "Approved", indication: "CKD + Type 2 Diabetes", therapeuticArea: "Nephrology/Renal", company: "Bayer", companyTrackRecord: 'fast', nctId: "NCT02540993", scores: calculateProbabilityScores("Approved", "CKD", "Nephrology"), marketData: generateMarketProjections("Finerenone", "Approved", "CKD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Non-steroidal MRA", administration: "Oral daily", keyAdvantage: "Cardiorenal protection" } },
  { id: "ext-cm-066", name: "Dapagliflozin (CKD)", phase: "Approved", indication: "Chronic Kidney Disease", therapeuticArea: "Nephrology/Renal", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT03036150", scores: calculateProbabilityScores("Approved", "CKD", "Nephrology"), marketData: generateMarketProjections("Dapagliflozin CKD", "Approved", "CKD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "SGLT2 inhibitor", administration: "Oral daily", keyAdvantage: "CKD independent of DM" } },
  { id: "ext-cm-067", name: "Empagliflozin (CKD)", phase: "Approved", indication: "Chronic Kidney Disease", therapeuticArea: "Nephrology/Renal", company: "Boehringer/Lilly", companyTrackRecord: 'fast', nctId: "NCT03594110", scores: calculateProbabilityScores("Approved", "CKD", "Nephrology"), marketData: generateMarketProjections("Empagliflozin CKD", "Approved", "CKD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "SGLT2 inhibitor", administration: "Oral daily", keyAdvantage: "EMPA-KIDNEY" } },
  { id: "ext-cm-068", name: "Daprodustat", phase: "Approved", indication: "CKD Anemia", therapeuticArea: "Nephrology/Renal", company: "GSK", companyTrackRecord: 'fast', nctId: "NCT02879305", scores: calculateProbabilityScores("Approved", "CKD Anemia", "Nephrology"), marketData: generateMarketProjections("Daprodustat", "Approved", "CKD Anemia", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "HIF-PHI", administration: "Oral daily", keyAdvantage: "Oral ESA alternative" } },
  { id: "ext-cm-069", name: "Roxadustat", phase: "Approved", indication: "CKD Anemia", therapeuticArea: "Nephrology/Renal", company: "FibroGen/AstraZeneca", companyTrackRecord: 'average', nctId: "NCT02174627", scores: calculateProbabilityScores("Approved", "CKD Anemia", "Nephrology"), marketData: generateMarketProjections("Roxadustat", "Approved", "CKD Anemia", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "HIF-PHI", administration: "Oral 3x weekly", keyAdvantage: "First HIF-PHI" } },
  { id: "ext-cm-070", name: "Vadadustat", phase: "Approved", indication: "CKD Anemia", therapeuticArea: "Nephrology/Renal", company: "Akebia/Otsuka", companyTrackRecord: 'average', nctId: "NCT02892149", scores: calculateProbabilityScores("Approved", "CKD Anemia", "Nephrology"), marketData: generateMarketProjections("Vadadustat", "Approved", "CKD Anemia", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "HIF-PHI", administration: "Oral daily", keyAdvantage: "Daily dosing" } },
  
  // Hyperkalemia
  { id: "ext-cm-071", name: "Patiromer", phase: "Approved", indication: "Hyperkalemia", therapeuticArea: "Nephrology/Renal", company: "Vifor/CSL", companyTrackRecord: 'average', nctId: "NCT01371747", scores: calculateProbabilityScores("Approved", "Hyperkalemia", "Nephrology"), marketData: generateMarketProjections("Patiromer", "Approved", "Hyperkalemia", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "K+ binder", administration: "Oral powder", keyAdvantage: "Chronic use" } },
  { id: "ext-cm-072", name: "Sodium Zirconium Cyclosilicate", phase: "Approved", indication: "Hyperkalemia", therapeuticArea: "Nephrology/Renal", company: "AstraZeneca", companyTrackRecord: 'fast', nctId: "NCT02088073", scores: calculateProbabilityScores("Approved", "Hyperkalemia", "Nephrology"), marketData: generateMarketProjections("SZC", "Approved", "Hyperkalemia", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "K+ binder", administration: "Oral suspension", keyAdvantage: "Rapid onset" } },
  
  // IgA Nephropathy
  { id: "ext-cm-073", name: "Sparsentan", phase: "Approved", indication: "IgA Nephropathy", therapeuticArea: "Nephrology/Renal", company: "Travere", companyTrackRecord: 'average', nctId: "NCT03762850", scores: calculateProbabilityScores("Approved", "IgA Nephropathy", "Nephrology"), marketData: generateMarketProjections("Sparsentan", "Approved", "IgA Nephropathy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Dual ETAR/AT1R antagonist", administration: "Oral daily", keyAdvantage: "First IgAN approval" } },
  { id: "ext-cm-074", name: "Iptacopan", phase: "Phase III", indication: "IgA Nephropathy", therapeuticArea: "Nephrology/Renal", company: "Novartis", companyTrackRecord: 'fast', nctId: "NCT04578834", scores: calculateProbabilityScores("Phase III", "IgA Nephropathy", "Nephrology"), marketData: generateMarketProjections("Iptacopan IgAN", "Phase III", "IgA Nephropathy", 'fast'), overallScore: 0, drugInfo: { class: "Factor B inhibitor", administration: "Oral", keyAdvantage: "Complement AP inhibition" } },
  { id: "ext-cm-075", name: "Narsoplimab", phase: "Phase III", indication: "IgA Nephropathy", therapeuticArea: "Nephrology/Renal", company: "Omeros", companyTrackRecord: 'average', nctId: "NCT03608033", scores: calculateProbabilityScores("Phase III", "IgA Nephropathy", "Nephrology"), marketData: generateMarketProjections("Narsoplimab", "Phase III", "IgA Nephropathy", 'average'), overallScore: 0, drugInfo: { class: "Anti-MASP-2 antibody", administration: "IV", keyAdvantage: "Lectin pathway" } },
  { id: "ext-cm-076", name: "Budesonide Delayed-Release", phase: "Approved", indication: "IgA Nephropathy", therapeuticArea: "Nephrology/Renal", company: "Calliditas", companyTrackRecord: 'average', nctId: "NCT03643965", scores: calculateProbabilityScores("Approved", "IgA Nephropathy", "Nephrology"), marketData: generateMarketProjections("Nefecon", "Approved", "IgA Nephropathy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Targeted corticosteroid", administration: "Oral daily", keyAdvantage: "Gut-targeted release" } },
  { id: "ext-cm-077", name: "Atacicept (IgAN)", phase: "Phase III", indication: "IgA Nephropathy", therapeuticArea: "Nephrology/Renal", company: "Vera Therapeutics", companyTrackRecord: 'average', nctId: "NCT04716231", scores: calculateProbabilityScores("Phase III", "IgA Nephropathy", "Nephrology"), marketData: generateMarketProjections("Atacicept IgAN", "Phase III", "IgA Nephropathy", 'average'), overallScore: 0, drugInfo: { class: "APRIL/BLyS inhibitor", administration: "SC weekly", keyAdvantage: "Gd-IgA1 reduction" } },
  { id: "ext-cm-078", name: "Sibeprenlimab", phase: "Phase III", indication: "IgA Nephropathy", therapeuticArea: "Nephrology/Renal", company: "AbbVie", companyTrackRecord: 'fast', nctId: "NCT05248646", scores: calculateProbabilityScores("Phase III", "IgA Nephropathy", "Nephrology"), marketData: generateMarketProjections("Sibeprenlimab", "Phase III", "IgA Nephropathy", 'fast'), overallScore: 0, drugInfo: { class: "Anti-APRIL antibody", administration: "SC monthly", keyAdvantage: "Selective APRIL blockade" } },
  
  // Gout
  { id: "ext-cm-079", name: "Pegloticase + Methotrexate", phase: "Approved", indication: "Refractory Gout", therapeuticArea: "Rheumatology", company: "Horizon/Amgen", companyTrackRecord: 'fast', nctId: "NCT03994731", scores: calculateProbabilityScores("Approved", "Gout", "Rheumatology"), marketData: generateMarketProjections("Pegloticase+MTX", "Approved", "Gout", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PEGylated uricase", administration: "IV every 2 weeks", keyAdvantage: "Improved durability" } },
  { id: "ext-cm-080", name: "SEL-212", phase: "Phase III", indication: "Refractory Gout", therapeuticArea: "Rheumatology", company: "Selecta", companyTrackRecord: 'average', nctId: "NCT04513366", scores: calculateProbabilityScores("Phase III", "Gout", "Rheumatology"), marketData: generateMarketProjections("SEL-212", "Phase III", "Gout", 'average'), overallScore: 0, drugInfo: { class: "Uricase + ImmTOR", administration: "IV monthly", keyAdvantage: "Reduced immunogenicity" } },
  
  // Dyslipidemia/ASCVD Additional
  { id: "ext-cm-081", name: "Icosapent Ethyl", phase: "Approved", indication: "Cardiovascular Risk Reduction", therapeuticArea: "Cardiovascular", company: "Amarin", companyTrackRecord: 'average', nctId: "NCT01492361", scores: calculateProbabilityScores("Approved", "ASCVD", "Cardiology"), marketData: generateMarketProjections("Vascepa", "Approved", "ASCVD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Pure EPA omega-3", administration: "Oral twice daily", keyAdvantage: "REDUCE-IT outcomes" } },
  { id: "ext-cm-082", name: "Pemafibrate", phase: "Phase III", indication: "Hypertriglyceridemia", therapeuticArea: "Cardiovascular", company: "Kowa", companyTrackRecord: 'average', nctId: "NCT03071692", scores: calculateProbabilityScores("Phase III", "Hypertriglyceridemia", "Cardiology"), marketData: generateMarketProjections("Pemafibrate", "Phase III", "Hypertriglyceridemia", 'average'), overallScore: 0, drugInfo: { class: "Selective PPARα modulator", administration: "Oral", keyAdvantage: "Selective SPPARMα" } },
  { id: "ext-cm-083", name: "Mipomersen", phase: "Approved", indication: "Homozygous FH", therapeuticArea: "Cardiovascular", company: "Ionis/Kastle", companyTrackRecord: 'fast', nctId: "NCT00607373", scores: calculateProbabilityScores("Approved", "FH", "Cardiology"), marketData: generateMarketProjections("Mipomersen", "Approved", "FH", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Antisense targeting ApoB", administration: "SC weekly", keyAdvantage: "HoFH option" } },
  { id: "ext-cm-084", name: "Lomitapide", phase: "Approved", indication: "Homozygous FH", therapeuticArea: "Cardiovascular", company: "Aegerion", companyTrackRecord: 'average', nctId: "NCT00730236", scores: calculateProbabilityScores("Approved", "FH", "Cardiology"), marketData: generateMarketProjections("Lomitapide", "Approved", "FH", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "MTP inhibitor", administration: "Oral daily", keyAdvantage: "Oral MTP inhibition" } },
  
  // Rare Metabolic
  { id: "ext-cm-085", name: "Pegvaliase", phase: "Approved", indication: "Phenylketonuria", therapeuticArea: "Endocrinology & Metabolism", company: "BioMarin", companyTrackRecord: 'average', nctId: "NCT01560286", scores: calculateProbabilityScores("Approved", "PKU", "Metabolic"), marketData: generateMarketProjections("Pegvaliase", "Approved", "PKU", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PEGylated PAL", administration: "SC daily", keyAdvantage: "Enzyme substitution" } },
  { id: "ext-cm-086", name: "Sapropterin", phase: "Approved", indication: "Phenylketonuria", therapeuticArea: "Endocrinology & Metabolism", company: "BioMarin", companyTrackRecord: 'average', nctId: "NCT00102219", scores: calculateProbabilityScores("Approved", "PKU", "Metabolic"), marketData: generateMarketProjections("Sapropterin", "Approved", "PKU", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "BH4 cofactor", administration: "Oral daily", keyAdvantage: "PAH enhancer" } },
  { id: "ext-cm-087", name: "Setmelanotide", phase: "Approved", indication: "POMC/LEPR Obesity", therapeuticArea: "Endocrinology & Metabolism", company: "Rhythm", companyTrackRecord: 'average', nctId: "NCT02896192", scores: calculateProbabilityScores("Approved", "Genetic Obesity", "Metabolic"), marketData: generateMarketProjections("Setmelanotide", "Approved", "Genetic Obesity", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "MC4R agonist", administration: "SC daily", keyAdvantage: "Genetic obesity" } },
  { id: "ext-cm-088", name: "Odevixibat", phase: "Approved", indication: "PFIC", therapeuticArea: "Gastroenterology & Hepatology", company: "Albireo/Ipsen", companyTrackRecord: 'average', nctId: "NCT03566238", scores: calculateProbabilityScores("Approved", "PFIC", "Metabolic"), marketData: generateMarketProjections("Odevixibat", "Approved", "PFIC", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "IBAT inhibitor", administration: "Oral daily", keyAdvantage: "Pruritus reduction" } },
  { id: "ext-cm-089", name: "Maralixibat", phase: "Approved", indication: "Alagille Syndrome", therapeuticArea: "Gastroenterology & Hepatology", company: "Mirum", companyTrackRecord: 'average', nctId: "NCT02160782", scores: calculateProbabilityScores("Approved", "Alagille", "Metabolic"), marketData: generateMarketProjections("Maralixibat", "Approved", "Alagille", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "IBAT inhibitor", administration: "Oral daily", keyAdvantage: "First Alagille therapy" } },
  { id: "ext-cm-090", name: "Olipudase alfa", phase: "Approved", indication: "ASMD (Niemann-Pick B)", therapeuticArea: "Endocrinology & Metabolism", company: "Sanofi", companyTrackRecord: 'fast', nctId: "NCT02004691", scores: calculateProbabilityScores("Approved", "ASMD", "Metabolic"), marketData: generateMarketProjections("Olipudase alfa", "Approved", "ASMD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "ERT (ASM enzyme)", administration: "IV every 2 weeks", keyAdvantage: "First ASMD ERT" } },
  
  // Peripheral Artery Disease
  { id: "ext-cm-091", name: "Vorapaxar", phase: "Approved", indication: "PAD/MI Prevention", therapeuticArea: "Cardiovascular", company: "Merck", companyTrackRecord: 'fast', nctId: "NCT00526474", scores: calculateProbabilityScores("Approved", "PAD", "Cardiology"), marketData: generateMarketProjections("Vorapaxar", "Approved", "PAD", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PAR-1 antagonist", administration: "Oral daily", keyAdvantage: "Anti-thrombotic" } },
  { id: "ext-cm-092", name: "Cilostazol", phase: "Approved", indication: "Intermittent Claudication", therapeuticArea: "Cardiovascular", company: "Otsuka", companyTrackRecord: 'average', nctId: "NCT00007969", scores: calculateProbabilityScores("Approved", "PAD", "Cardiology"), marketData: generateMarketProjections("Cilostazol", "Approved", "PAD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "PDE3 inhibitor", administration: "Oral twice daily", keyAdvantage: "Walking distance" } },
  
  // Venous Thromboembolism
  { id: "ext-cm-093", name: "Milvexian", phase: "Phase III", indication: "VTE Prevention", therapeuticArea: "Cardiovascular", company: "BMS/Janssen", companyTrackRecord: 'fast', nctId: "NCT05360017", scores: calculateProbabilityScores("Phase III", "VTE", "Cardiology"), marketData: generateMarketProjections("Milvexian", "Phase III", "VTE", 'fast'), overallScore: 0, drugInfo: { class: "Factor XIa inhibitor", administration: "Oral", keyAdvantage: "Reduced bleeding risk" } },
  { id: "ext-cm-094", name: "Asundexian", phase: "Phase III", indication: "Stroke Prevention in AF", therapeuticArea: "Cardiovascular", company: "Bayer", companyTrackRecord: 'fast', nctId: "NCT05686070", scores: calculateProbabilityScores("Phase III", "AF Stroke", "Cardiology"), marketData: generateMarketProjections("Asundexian", "Phase III", "AF Stroke", 'fast'), overallScore: 0, drugInfo: { class: "Factor XIa inhibitor", administration: "Oral once daily", keyAdvantage: "Bleeding reduction" } },
  { id: "ext-cm-095", name: "Abelacimab", phase: "Phase III", indication: "VTE Prevention", therapeuticArea: "Cardiovascular", company: "Anthos", companyTrackRecord: 'average', nctId: "NCT05171049", scores: calculateProbabilityScores("Phase III", "VTE", "Cardiology"), marketData: generateMarketProjections("Abelacimab", "Phase III", "VTE", 'average'), overallScore: 0, drugInfo: { class: "Anti-Factor XI antibody", administration: "SC monthly", keyAdvantage: "Monthly dosing" } },
  
  // Additional Metabolic
  { id: "ext-cm-096", name: "Givosiran", phase: "Approved", indication: "Acute Hepatic Porphyria", therapeuticArea: "Endocrinology & Metabolism", company: "Alnylam", companyTrackRecord: 'fast', nctId: "NCT03338816", scores: calculateProbabilityScores("Approved", "AHP", "Metabolic"), marketData: generateMarketProjections("Givosiran", "Approved", "AHP", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "RNAi targeting ALAS1", administration: "SC monthly", keyAdvantage: "Attack prevention" } },
  { id: "ext-cm-097", name: "Lumasiran", phase: "Approved", indication: "Primary Hyperoxaluria Type 1", therapeuticArea: "Nephrology/Renal", company: "Alnylam", companyTrackRecord: 'fast', nctId: "NCT03681184", scores: calculateProbabilityScores("Approved", "PH1", "Nephrology"), marketData: generateMarketProjections("Lumasiran", "Approved", "PH1", 'fast'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "RNAi targeting HAO1", administration: "SC monthly", keyAdvantage: "Oxalate reduction" } },
  { id: "ext-cm-098", name: "Nedosiran", phase: "Phase III", indication: "Primary Hyperoxaluria", therapeuticArea: "Nephrology/Renal", company: "Dicerna/Novo", companyTrackRecord: 'average', nctId: "NCT04042402", scores: calculateProbabilityScores("Phase III", "PH", "Nephrology"), marketData: generateMarketProjections("Nedosiran", "Phase III", "PH", 'average'), overallScore: 0, drugInfo: { class: "RNAi targeting LDHA", administration: "SC quarterly", keyAdvantage: "Quarterly dosing" } },
  { id: "ext-cm-099", name: "Stiripentol", phase: "Approved", indication: "Dravet + Metabolic Epilepsy", therapeuticArea: "Neurology/CNS", company: "Biocodex", companyTrackRecord: 'average', nctId: "NCT00490789", scores: calculateProbabilityScores("Approved", "Epilepsy", "Metabolic"), marketData: generateMarketProjections("Stiripentol", "Approved", "Epilepsy", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "GABA modulator", administration: "Oral", keyAdvantage: "Dravet adjunct" } },
  { id: "ext-cm-100", name: "Triheptanoin", phase: "Approved", indication: "Long-chain FAODs", therapeuticArea: "Endocrinology & Metabolism", company: "Ultragenyx", companyTrackRecord: 'average', nctId: "NCT01379625", scores: calculateProbabilityScores("Approved", "FAOD", "Metabolic"), marketData: generateMarketProjections("Triheptanoin", "Approved", "FAOD", 'average'), overallScore: 0, hasRetrospective: true, drugInfo: { class: "Medium-chain triglyceride", administration: "Oral", keyAdvantage: "Anaplerotic substrate" } },
];
